// AUTO-GENERATED by tools/gen_firmware_theme.py from tools/m5_theme.json -- DO NOT EDIT.
#pragma once
#include <cstdint>

// Colours (0xRRGGBB)
constexpr std::uint32_t COLOR_BG = 0x121820;
constexpr std::uint32_t COLOR_TEXT = 0xE7E9ED;
constexpr std::uint32_t COLOR_MUTED = 0x9FC2C8;
constexpr std::uint32_t COLOR_GOOD = 0x2E9E72;
constexpr std::uint32_t COLOR_WARN = 0xFF8C00;
constexpr std::uint32_t COLOR_BAD = 0xCC0000;
constexpr std::uint32_t COLOR_BLUE = 0x0055FF;
constexpr std::uint32_t COLOR_KLID = 0x6E7C80;
constexpr std::uint32_t CHIP_KLID_BG = 0x18271D;
constexpr std::uint32_t CHIP_KLID_TEXT = 0xCDEAD9;
constexpr std::uint32_t COLOR_TEAL = 0x4FD1C5;

// Layout / geometry (px)
constexpr int STATUS_H = 28;
constexpr int SPINE_W = 4;
constexpr int PLOT_X = 8;
constexpr int PLOT_Y = 33;
constexpr int PLOT_W = 224;
constexpr int PLOT_H = 47;
constexpr int EFEKT_TOP = 30;
constexpr int EFEKT_BOT = 89;
constexpr int PLOT_TOP = 36;
constexpr int PLOT_PEAK_PAD = 2;
constexpr int PALETTE_Y = 82;
constexpr int ROW_Y = 93;
constexpr int ROW_H = 18;
constexpr int ROW_VISIBLE = 2;
constexpr int PLOT_MAX_CYCLES = 3;
