# Auto-generated by UI Designer
# Scene: dashboard
# Generated: 2025-11-16 13:34:21

from dataclasses import dataclass
from typing import List


@dataclass
class Widget:
    type: str
    x: int
    y: int
    width: int
    height: int
    text: str = ''
    style: str = 'default'
    color_fg: str = 'white'
    color_bg: str = 'black'
    border: bool = True
    align: str = 'left'


def create_dashboard_scene() -> List[Widget]:
    """Create dashboard scene widgets"""
    return [
        Widget(
            type='label',
            x=0,
            y=0,
            width=128,
            height=10,
            text='ESP32 Dashboard',
            style='bold',
            color_fg='cyan',
            border=False,
            align='center',
        ),
        Widget(
            type='panel',
            x=8,
            y=12,
            width=120,
            height=50,
            text='Status: ONLINE',
            color_bg='blue',
        ),
        Widget(
            type='button',
            x=8,
            y=24,
            width=40,
            height=12,
            text='START',
            color_fg='black',
            color_bg='green',
            align='center',
        ),
        Widget(
            type='button',
            x=52,
            y=24,
            width=40,
            height=12,
            text='START',
            color_fg='black',
            color_bg='green',
            align='center',
        ),
        Widget(
            type='progressbar',
            x=8,
            y=40,
            width=100,
            height=8,
            color_fg='green',
        ),
        Widget(
            type='gauge',
            x=80,
            y=12,
            width=40,
            height=20,
            color_fg='yellow',
        ),
        Widget(
            type='gauge',
            x=80,
            y=40,
            width=40,
            height=20,
            color_fg='yellow',
        ),
    ]


if __name__ == '__main__':
    widgets = create_dashboard_scene()
    print(f'Created {len(widgets)} widgets for dashboard scene')