[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf

[env:ui-sim]
platform = native
build_flags = 
    -std=c11
    -D_WIN32
build_src_filter = 
    +<../sim/>
    -<*>
build_unflags = -std=gnu++11
extra_scripts = post:run_simulator.py
