[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf

[env:native]
platform = native
build_flags =
    -Itest/stubs
test_filter =
    test_ui_render_swbuf
    test_ui_core
build_src_filter =
    +<services/ui/ui_core.c>
    +<ui_render_swbuf.c>
    +<ui_render.c>
    +<ui_design.c>
