# Auto-generated by UI Designer
# Scene: main
# Generated: 2025-11-21 22:10:10

from dataclasses import dataclass
from typing import List


@dataclass
class Widget:
    type: str
    x: int
    y: int
    width: int
    height: int
    text: str = ''
    style: str = 'default'
    color_fg: str = 'white'
    color_bg: str = 'black'
    border: bool = True
    align: str = 'left'


def create_main_scene() -> List[Widget]:
    """Create main scene widgets"""
    return [
        Widget(
            type='label',
            x=0,
            y=4,
            width=128,
            height=10,
            text='Dashboard',
            style='bold',
            color_fg='cyan',
            border=False,
            align='center',
        ),
        Widget(
            type='button',
            x=44,
            y=18,
            width=40,
            height=12,
            text='Start',
            color_fg='black',
            color_bg='green',
            align='center',
        ),
        Widget(
            type='gauge',
            x=44,
            y=34,
            width=40,
            height=20,
            color_fg='yellow',
        ),
        Widget(
            type='button',
            x=44,
            y=58,
            width=40,
            height=12,
            text='Start',
            color_fg='black',
            color_bg='green',
            align='center',
        ),
    ]


if __name__ == '__main__':
    widgets = create_main_scene()
    print(f'Created {len(widgets)} widgets for main scene')