# Auto-generated by UI Designer
# Scene: test
# Generated: 2025-11-23 20:47:03

from dataclasses import dataclass
from typing import List


@dataclass
class Widget:
    type: str
    x: int
    y: int
    width: int
    height: int
    text: str = ''
    style: str = 'default'
    color_fg: str = 'white'
    color_bg: str = 'black'
    border: bool = True
    align: str = 'left'


def create_test_scene() -> List[Widget]:
    """Create test scene widgets"""
    return [
        Widget(
            type='label',
            x=29,
            y=9,
            width=128,
            height=10,
            text='Title',
            style='bold',
            color_fg='cyan',
            border=False,
            align='center',
        ),
        Widget(
            type='button',
            x=95,
            y=8,
            width=40,
            height=12,
            text='OK',
            color_fg='black',
            color_bg='green',
            align='center',
        ),
        Widget(
            type='button',
            x=73,
            y=8,
            width=40,
            height=12,
            text='Cancel',
            color_bg='red',
            align='center',
        ),
        Widget(
            type='panel',
            x=4,
            y=66,
            width=120,
            height=50,
            color_bg='blue',
        ),
        Widget(
            type='progressbar',
            x=14,
            y=124,
            width=100,
            height=8,
            color_fg='green',
        ),
        Widget(
            type='label',
            x=0,
            y=140,
            width=128,
            height=10,
            text='Title',
            style='bold',
            color_fg='cyan',
            border=False,
            align='center',
        ),
    ]


if __name__ == '__main__':
    widgets = create_test_scene()
    print(f'Created {len(widgets)} widgets for test scene')