"""
Integration of image_tools into UI Designer
Provides bitmap icon export and font management for ESPOS displays
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING, Optional, List, Dict

if TYPE_CHECKING:
    from PIL import Image as PILImage

try:
    from PIL import Image
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False
    Image = None  # type: ignore


# ============================================================
# Icon Bitmap Export Integration
# ============================================================

class IconBitmapExporter:
    """Exports UI icons as deduplicated C bitmap arrays"""
    
    def __init__(self):
        if not PIL_AVAILABLE:
            raise ImportError("PIL/Pillow required for bitmap export")
        
        from tools.xbmp_dedup import XBMPManager
        self.xbmp = XBMPManager(default_dither="floyd-steinberg")
        self.icon_refs: Dict[str, str] = {}  # name -> bitmap_ref
    
    def add_icon_from_file(self, icon_path: str, icon_name: str, size: int = 16) -> str:
        """
        Add icon from PNG/JPG file with resizing and dithering
        
        Args:
            icon_path: Path to image file
            icon_name: Name for C reference (e.g., "wifi", "battery")
            size: Target size in pixels (16, 24, 32)
        
        Returns:
            Reference ID for bitmap array
        """
        img = Image.open(icon_path).resize((size, size)).convert("L")
        ref = self.xbmp.add_icon_from_pil(img)
        self.icon_refs[icon_name] = ref
        return ref
    
    def add_material_icon(self, symbol: str, icon_name: str, size: int = 24) -> Optional[str]:
        """
        Add Material Icon from existing icon files
        
        Args:
            symbol: Material icon symbol (e.g., "mi_home_24px")
            icon_name: Name for C reference
            size: Target size
        
        Returns:
            Reference ID or None if icon file not found
        """
        # Look for icon in common paths
        search_paths = [
            Path("assets/icons"),
            Path("ui/icons"),
            Path(f"assets/material_icons/{size}px"),
        ]
        
        for base_path in search_paths:
            icon_file = base_path / f"{symbol}.png"
            if icon_file.exists():
                return self.add_icon_from_file(str(icon_file), icon_name, size)
        
        return None
    
    def export_to_header(self, output_path: str = "") -> str:
        """
        Export all icons as C header file
        
        Args:
            output_path: Output file path (empty string = return only, don't save)
        
        Returns:
            Generated C code
        """
        c_code = self.xbmp.generate_c_code()
        
        # Add icon references at the end
        header = [
            "#pragma once",
            "#include <stdint.h>",
            "",
            "/* Auto-generated icon bitmaps for ESPOS UI */",
            "/* Generated by UI Designer - Image Tools Integration */",
            "",
        ]
        
        footer = [
            "",
            "/* Icon reference lookup table */",
            "typedef struct {",
            "    const char* name;",
            "    const unsigned char* bitmap;",
            "    uint8_t width;",
            "    uint8_t height;",
            "} IconRef;",
            "",
        ]
        
        # Add individual icon references
        refs_list = []
        for name, ref in self.icon_refs.items():
            # Extract size from bitmap comment (e.g., "/* 16x16, 32 bytes */")
            # For now, assume 16x16 or 24x24
            size = 16  # TODO: parse from XBMP manager
            footer.append(f"#define ICON_{name.upper()} {ref}")
            refs_list.append(f'    {{"{name}", {ref}, {size}, {size}}}')
        
        footer.extend([
            "",
            "static const IconRef UI_ICONS[] = {",
            ",\n".join(refs_list),
            "};",
            "",
            f"#define UI_ICON_COUNT {len(refs_list)}",
        ])
        
        full_code = "\n".join(header) + c_code + "\n".join(footer)
        
        if output_path:
            Path(output_path).write_text(full_code, encoding="utf-8")
        
        return full_code
    
    def get_stats(self) -> Dict[str, int]:
        """Get deduplication statistics"""
        return {
            "total_icons": len(self.icon_refs),
            "unique_bitmaps": len(self.xbmp.bitmaps),
            "duplicates_saved": len(self.icon_refs) - len(self.xbmp.bitmaps),
            "memory_saved_percent": int((1 - len(self.xbmp.bitmaps) / max(1, len(self.icon_refs))) * 100)
        }


# ============================================================
# Font Export Integration
# ============================================================

class FontExporter:
    """Exports BDF fonts for ESPOS displays"""
    
    def __init__(self):
        from tools.bdf_font import BDFFont
        self.BDFFont = BDFFont
        self.loaded_fonts: Dict[str, 'BDFFont'] = {}
    
    def load_font(self, bdf_path: str, font_name: str) -> 'BDFFont':
        """Load BDF font file"""
        font = self.BDFFont.load(bdf_path)
        self.loaded_fonts[font_name] = font
        return font
    
    def export_font_subset(
        self, 
        font_name: str, 
        text_sample: str,
        output_path: Optional[str] = None
    ) -> str:
        """
        Export font with only characters used in text_sample
        
        Args:
            font_name: Name of loaded font
            text_sample: Text containing all needed characters
            output_path: Optional output file path
        
        Returns:
            Generated C code
        """
        from tools.bdf_font_export import export_font_subset
        
        if font_name not in self.loaded_fonts:
            raise ValueError(f"Font '{font_name}' not loaded")
        
        font = self.loaded_fonts[font_name]
        c_code = export_font_subset(font, text_sample, font_name)
        
        if output_path:
            Path(output_path).write_text(c_code, encoding="utf-8")
        
        return c_code
    
    def export_full_font(
        self,
        font_name: str,
        output_path: Optional[str] = None,
        charset: Optional[str] = None
    ) -> str:
        """
        Export complete font (or specific charset)
        
        Args:
            font_name: Name of loaded font
            output_path: Optional output file path
            charset: Optional charset string (default: ASCII printable)
        
        Returns:
            Generated C code
        """
        from tools.bdf_font_export import export_font_to_c
        
        if font_name not in self.loaded_fonts:
            raise ValueError(f"Font '{font_name}' not loaded")
        
        font = self.loaded_fonts[font_name]
        
        if charset is None:
            # Default: ASCII printable characters
            charset = "".join(chr(i) for i in range(32, 127))
        
        c_code = export_font_to_c(font, font_name, charset)
        
        if output_path:
            Path(output_path).write_text(c_code, encoding="utf-8")
        
        return c_code


# ============================================================
# UI Designer Integration Helpers
# ============================================================

def export_current_scene_assets(designer, output_dir: str) -> Dict[str, str]:
    """
    Export all assets (icons, fonts) used in current scene
    
    Args:
        designer: UIDesigner instance
        output_dir: Output directory for generated files
    
    Returns:
        Dict of generated files {filename: content}
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    generated_files = {}
    
    # TODO: Scan scene for used icons and text
    # For now, just demonstrate the API
    
    # Example: Export common UI icons
    if PIL_AVAILABLE:
        try:
            exporter = IconBitmapExporter()
            
            # Check if user has icon assets
            icon_dir = Path("assets/icons")
            if icon_dir.exists():
                for icon_file in icon_dir.glob("*.png"):
                    name = icon_file.stem
                    try:
                        exporter.add_icon_from_file(str(icon_file), name)
                    except Exception as e:
                        print(f"[WARN] Failed to add icon {name}: {e}")
            
            # Generate header
            icon_header = output_path / "ui_icons.h"
            c_code = exporter.export_to_header(str(icon_header))
            generated_files["ui_icons.h"] = c_code
            
            # Print stats
            stats = exporter.get_stats()
            print(f"[OK] Icon export: {stats['total_icons']} icons, "
                  f"{stats['unique_bitmaps']} unique, "
                  f"{stats['memory_saved_percent']}% saved")
        
        except Exception as e:
            print(f"[WARN] Icon export failed: {e}")
    
    return generated_files


def find_bdf_fonts() -> List[str]:
    """Find available BDF fonts in common locations"""
    search_paths = [
        Path("fonts"),
        Path("assets/fonts"),
        Path("/usr/share/fonts/X11/misc"),  # Linux X11
        Path.home() / ".fonts",
    ]
    
    bdf_files = []
    for base_path in search_paths:
        if base_path.exists():
            bdf_files.extend([str(f) for f in base_path.glob("*.bdf")])
    
    return sorted(bdf_files)


# ============================================================
# Tkinter UI Extensions (if TK available)
# ============================================================

def create_bitmap_export_dialog(root, preview_window):
    """
    Create dialog for bitmap icon export
    (To be integrated into IconPaletteWindow)
    """
    try:
        import tkinter as tk
        from tkinter import ttk, filedialog, messagebox
    except ImportError:
        return None
    
    dialog = tk.Toplevel(root)
    dialog.title("Export Icons as Bitmaps")
    dialog.geometry("500x400")
    
    # Instructions
    ttk.Label(
        dialog,
        text="Export Material Icons as C bitmap arrays for embedded displays",
        wraplength=450
    ).pack(pady=10)
    
    # Icon selection list
    frame = ttk.Frame(dialog)
    frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=5)
    
    ttk.Label(frame, text="Select icons to export:").pack(anchor=tk.W)
    
    listbox = tk.Listbox(frame, selectmode=tk.MULTIPLE, height=10)
    listbox.pack(fill=tk.BOTH, expand=True)
    
    # Populate with available icons
    from tools.ui_icons import MATERIAL_ICONS
    for icon in MATERIAL_ICONS:
        listbox.insert(tk.END, f"{icon['name']} ({icon['symbol']})")
    
    # Export options
    opt_frame = ttk.Frame(dialog)
    opt_frame.pack(fill=tk.X, padx=10, pady=5)
    
    size_var = tk.StringVar(value="16")
    ttk.Label(opt_frame, text="Size:").pack(side=tk.LEFT)
    ttk.Radiobutton(opt_frame, text="16x16", variable=size_var, value="16").pack(side=tk.LEFT)
    ttk.Radiobutton(opt_frame, text="24x24", variable=size_var, value="24").pack(side=tk.LEFT)
    ttk.Radiobutton(opt_frame, text="32x32", variable=size_var, value="32").pack(side=tk.LEFT)
    
    # Export button
    def do_export():
        selected = listbox.curselection()
        if not selected:
            messagebox.showwarning("No Selection", "Please select icons to export")
            return
        
        output_file = filedialog.asksaveasfilename(
            defaultextension=".h",
            filetypes=[("Header", "*.h"), ("All", "*.*")],
            initialfile="ui_icons.h"
        )
        
        if not output_file:
            return
        
        try:
            exporter = IconBitmapExporter()
            size = int(size_var.get())
            
            # TODO: Add selected icons from actual PNG files
            # For now, show placeholder
            messagebox.showinfo(
                "Export",
                f"Would export {len(selected)} icons at {size}x{size}px\n"
                f"to: {output_file}\n\n"
                "Implementation requires PNG icon assets."
            )
            
        except Exception as e:
            messagebox.showerror("Export Failed", str(e))
    
    btn_frame = ttk.Frame(dialog)
    btn_frame.pack(fill=tk.X, padx=10, pady=10)
    
    ttk.Button(btn_frame, text="Export", command=do_export).pack(side=tk.LEFT, padx=5)
    ttk.Button(btn_frame, text="Close", command=dialog.destroy).pack(side=tk.LEFT)
    
    return dialog


# ============================================================
# CLI Commands (for automation)
# ============================================================

def cli_export_icons(icon_dir: str, output_file: str, size: int = 16):
    """
    Command-line icon export
    
    Usage:
        python -c "from ui_designer_image_tools import cli_export_icons; 
                   cli_export_icons('assets/icons', 'output/icons.h', 16)"
    """
    if not PIL_AVAILABLE:
        print("[ERROR] PIL/Pillow not installed")
        return
    
    exporter = IconBitmapExporter()
    icon_path = Path(icon_dir)
    
    if not icon_path.exists():
        print(f"[ERROR] Icon directory not found: {icon_dir}")
        return
    
    count = 0
    for icon_file in icon_path.glob("*.png"):
        name = icon_file.stem
        try:
            exporter.add_icon_from_file(str(icon_file), name, size)
            count += 1
        except Exception as e:
            print(f"[WARN] Skipped {name}: {e}")
    
    if count == 0:
        print("[ERROR] No icons found")
        return
    
    exporter.export_to_header(output_file)
    stats = exporter.get_stats()
    
    print(f"[OK] Exported {count} icons to {output_file}")
    print(f"     Unique bitmaps: {stats['unique_bitmaps']}")
    print(f"     Memory saved: {stats['memory_saved_percent']}%")


def cli_export_font(bdf_file: str, output_file: str, text_sample: Optional[str] = None):
    """
    Command-line font export
    
    Usage:
        python -c "from ui_designer_image_tools import cli_export_font;
                   cli_export_font('fonts/terminus-12.bdf', 'output/font.h', 'Hello')"
    """
    font_exporter = FontExporter()
    
    if not Path(bdf_file).exists():
        print(f"[ERROR] Font file not found: {bdf_file}")
        return
    
    font_name = Path(bdf_file).stem
    font = font_exporter.load_font(bdf_file, font_name)
    
    if text_sample:
        # Subset export
        c_code = font_exporter.export_font_subset(font_name, text_sample, output_file)
        print(f"[OK] Exported font subset ({len(set(text_sample))} unique chars) to {output_file}")
    else:
        # Full ASCII export
        c_code = font_exporter.export_full_font(font_name, output_file)
        print(f"[OK] Exported full font to {output_file}")


if __name__ == "__main__":
    # Demo usage
    print("UI Designer Image Tools Integration")
    print("=" * 50)
    
    if PIL_AVAILABLE:
        print("✓ PIL/Pillow available")
    else:
        print("✗ PIL/Pillow not installed")
    
    # Find available fonts
    bdf_fonts = find_bdf_fonts()
    print(f"\nFound {len(bdf_fonts)} BDF fonts:")
    for font in bdf_fonts[:5]:
        print(f"  - {font}")
    if len(bdf_fonts) > 5:
        print(f"  ... and {len(bdf_fonts) - 5} more")
    
    print("\nUsage examples:")
    print("  1. Export icons: python -c 'from ui_designer_image_tools import cli_export_icons; cli_export_icons(...)'")
    print("  2. Export font:  python -c 'from ui_designer_image_tools import cli_export_font; cli_export_font(...)'")
    print("  3. In UI Designer: Use 'Export Bitmaps' button in Icon Palette")
