import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from ui_designer import UIDesigner, WidgetConfig


def _designer_with_scene():
    designer = UIDesigner(10, 10)
    scene = designer.create_scene("main")
    designer.current_scene = scene.name
    scene.widgets.append(WidgetConfig(type="label", x=1, y=2, width=3, height=4, text="hi"))
    return designer, scene


def test_generate_imports_returns_header_and_widget_dataclass():
    designer, scene = _designer_with_scene()
    lines = designer._generate_imports(scene)
    text = "\n".join(lines)
    assert "# Auto-generated by UI Designer" in text
    assert "from dataclasses import dataclass" in text
    assert "class Widget" in text


def test_generate_widget_code_includes_overrides():
    designer, _ = _designer_with_scene()
    widget = WidgetConfig(
        type="button",
        x=5,
        y=6,
        width=7,
        height=8,
        text="Click",
        style="bold",
        color_fg="red",
        color_bg="blue",
        border=False,
        align="center",
    )
    lines = designer._generate_widget_code(widget)
    text = "\n".join(lines)
    assert "type='button'" in text
    assert "text='Click'" in text
    assert "style='bold'" in text
    assert "color_fg='red'" in text
    assert "color_bg='blue'" in text
    assert "border=False" in text
    assert "align='center'" in text


def test_generate_scene_init_wraps_all_widgets():
    designer, scene = _designer_with_scene()
    lines = designer._generate_scene_init(scene)
    text = "\n".join(lines)
    assert f"create_{scene.name.lower()}_scene" in text
    assert text.count("Widget(") == len(scene.widgets)
    assert "if __name__ == '__main__':" in text


def test_generate_python_code_combines_sections():
    designer, scene = _designer_with_scene()
    code = designer.generate_python_code(scene.name)
    assert "Auto-generated by UI Designer" in code
    assert f"create_{scene.name.lower()}_scene" in code
    assert "Widget(" in code
