import json
import sys
import tempfile
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from tools.ui_codegen import generate_ui_design_pair
from ui_designer import UIDesigner, WidgetConfig


def _designer_with_scene():
    designer = UIDesigner(10, 10)
    scene = designer.create_scene("main")
    designer.current_scene = scene.name
    scene.widgets.append(WidgetConfig(type="label", x=1, y=2, width=3, height=4, text="hi"))
    return designer, scene


def test_generate_imports_returns_header_and_widget_dataclass():
    designer, scene = _designer_with_scene()
    lines = designer._generate_imports(scene)
    text = "\n".join(lines)
    assert "# Auto-generated by UI Designer" in text
    assert "from dataclasses import dataclass" in text
    assert "class Widget" in text


def test_generate_widget_code_includes_overrides():
    designer, _ = _designer_with_scene()
    widget = WidgetConfig(
        type="button",
        x=5,
        y=6,
        width=7,
        height=8,
        text="Click",
        style="bold",
        color_fg="red",
        color_bg="blue",
        border=False,
        align="center",
    )
    lines = designer._generate_widget_code(widget)
    text = "\n".join(lines)
    assert "type='button'" in text
    assert "text='Click'" in text
    assert "style='bold'" in text
    assert "color_fg='red'" in text
    assert "color_bg='blue'" in text
    assert "border=False" in text
    assert "align='center'" in text


def test_generate_scene_init_wraps_all_widgets():
    designer, scene = _designer_with_scene()
    lines = designer._generate_scene_init(scene)
    text = "\n".join(lines)
    assert f"create_{scene.name.lower()}_scene" in text
    assert text.count("Widget(") == len(scene.widgets)
    assert "if __name__ == '__main__':" in text


def test_generate_python_code_combines_sections():
    designer, scene = _designer_with_scene()
    code = designer.generate_python_code(scene.name)
    assert "Auto-generated by UI Designer" in code
    assert f"create_{scene.name.lower()}_scene" in code
    assert "Widget(" in code


# ── items ↔ text sync ──────────────────────────────────────────────────


def test_items_populates_text_for_list_widget():
    w = WidgetConfig(
        type="list", x=0, y=0, width=80, height=40,
        items=["Alpha", "Beta", "Gamma"],
    )
    assert w.text == "Alpha\nBeta\nGamma"


def test_text_populates_items_for_list_widget():
    w = WidgetConfig(
        type="list", x=0, y=0, width=80, height=40,
        text="One\nTwo\nThree",
    )
    assert w.items == ["One", "Two", "Three"]


def test_items_takes_precedence_over_text():
    w = WidgetConfig(
        type="list", x=0, y=0, width=80, height=40,
        items=["A", "B"], text="X\nY\nZ",
    )
    assert w.text == "A\nB"
    assert w.items == ["A", "B"]


def test_items_ignored_for_non_list_widget():
    w = WidgetConfig(
        type="label", x=0, y=0, width=80, height=16,
        items=["A", "B"], text="hello",
    )
    assert w.text == "hello"


def test_empty_items_no_text_stays_empty():
    w = WidgetConfig(type="list", x=0, y=0, width=80, height=40)
    assert w.items == []
    assert w.text == ""


# ── C codegen: LIST with items ─────────────────────────────────────────


def _codegen_for_widgets(widgets):
    data = {"scenes": {"main": {"name": "main", "width": 128, "height": 64, "widgets": widgets}}}
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:
        json.dump(data, f)
        f.flush()
        src, _hdr = generate_ui_design_pair(Path(f.name), scene_name="main", source_label="t")
    return src


def test_codegen_list_items_to_text():
    src = _codegen_for_widgets([
        {"type": "list", "x": 0, "y": 0, "width": 80, "height": 40,
         "items": ["Foo", "Bar", "Baz"]},
    ])
    assert "UIW_LIST" in src
    assert "Foo\\nBar\\nBaz" in src


def test_codegen_list_text_passthrough():
    src = _codegen_for_widgets([
        {"type": "list", "x": 0, "y": 0, "width": 80, "height": 40,
         "text": "X\nY"},
    ])
    assert "UIW_LIST" in src
    assert "X\\nY" in src


def test_codegen_toggle_checked():
    src = _codegen_for_widgets([
        {"type": "toggle", "x": 0, "y": 0, "width": 60, "height": 14,
         "text": "WiFi", "checked": True},
    ])
    assert "UIW_TOGGLE" in src
    assert ".checked = 1" in src


# ── Codegen edge cases: LIST and TOGGLE ────────────────────────────────


def test_codegen_toggle_checked_false():
    src = _codegen_for_widgets([
        {"type": "toggle", "x": 0, "y": 0, "width": 60, "height": 14,
         "text": "Off", "checked": False},
    ])
    assert "UIW_TOGGLE" in src
    assert ".checked = 0" in src or ".checked" not in src


def test_codegen_list_empty_items():
    src = _codegen_for_widgets([
        {"type": "list", "x": 0, "y": 0, "width": 80, "height": 40,
         "items": []},
    ])
    assert "UIW_LIST" in src


def test_codegen_list_items_special_chars():
    """Items with quotes and backslash must be escaped in C output."""
    src = _codegen_for_widgets([
        {"type": "list", "x": 0, "y": 0, "width": 80, "height": 40,
         "items": ['Say "hello"', "path\\dir"]},
    ])
    assert "UIW_LIST" in src
    # The C string must contain escaped quotes/backslashes
    assert '\\"' in src or "hello" in src


def test_codegen_list_single_item():
    src = _codegen_for_widgets([
        {"type": "list", "x": 0, "y": 0, "width": 80, "height": 40,
         "items": ["Only"]},
    ])
    assert "UIW_LIST" in src
    assert "Only" in src


def test_codegen_list_many_items():
    items = [f"Item{i}" for i in range(20)]
    src = _codegen_for_widgets([
        {"type": "list", "x": 0, "y": 0, "width": 80, "height": 40,
         "items": items},
    ])
    assert "UIW_LIST" in src
    assert "Item0" in src
    assert "Item19" in src


def test_codegen_toggle_no_text():
    src = _codegen_for_widgets([
        {"type": "toggle", "x": 0, "y": 0, "width": 60, "height": 14,
         "checked": True},
    ])
    assert "UIW_TOGGLE" in src
    assert ".checked = 1" in src
