from ui_designer import UIDesigner, WidgetConfig


def _basic_designer():
    d = UIDesigner(10, 10)
    sc = d.create_scene("main")
    d.current_scene = sc.name
    sc.widgets.append(WidgetConfig(type="label", x=1, y=2, width=3, height=4, text="Hi"))
    sc.widgets.append(WidgetConfig(type="box", x=5, y=6, width=7, height=8, border=False))
    return d, sc


def test_generate_imports_has_header_and_dataclass():
    designer, scene = _basic_designer()
    lines = designer._generate_imports(scene)
    assert lines[0].startswith("# Auto-generated")
    assert "dataclass" in "\n".join(lines)
    assert "class Widget:" in "\n".join(lines)


def test_generate_widget_code_respects_overrides():
    designer, _ = _basic_designer()
    widget = WidgetConfig(
        type="button",
        x=1,
        y=2,
        width=3,
        height=4,
        text="Click",
        style="bold",
        color_fg="red",
        color_bg="blue",
        border=False,
        align="center",
    )
    lines = designer._generate_widget_code(widget)
    block = "\n".join(lines)
    assert "type='button'" in block
    assert "text='Click'" in block
    assert "style='bold'" in block
    assert "color_fg='red'" in block
    assert "color_bg='blue'" in block
    assert "border=False" in block
    assert "align='center'" in block


def test_generate_scene_init_renders_all_widgets():
    designer, scene = _basic_designer()
    lines = designer._generate_scene_init(scene)
    text = "\n".join(lines)
    assert "create_main_scene" in text
    assert text.count("Widget(") == len(scene.widgets)
    assert "if __name__ == '__main__':" in text


def test_generate_python_code_full_output():
    designer, scene = _basic_designer()
    code = designer.generate_python_code(scene.name)
    assert "Auto-generated by UI Designer" in code
    assert f"create_{scene.name.lower()}_scene" in code
    assert "Widget(" in code
