#include "unity.h"

#ifdef ESP_PLATFORM

void test_ui_nav_first_focus_in_rect_filters(void);
void test_ui_nav_move_focus_in_rect_cycles_inside_bounds(void);
void test_ui_nav_move_focus_in_rect_from_outside_picks_first(void);
void test_is_focusable_null_returns_false(void);
void test_is_focusable_button_returns_true(void);
void test_is_focusable_label_returns_false(void);
void test_is_focusable_checkbox_returns_true(void);
void test_is_focusable_radiobutton_returns_true(void);
void test_is_focusable_slider_returns_true(void);
void test_is_focusable_invisible_button_returns_false(void);
void test_is_focusable_disabled_button_returns_false(void);
void test_is_focusable_panel_returns_false(void);
void test_is_focusable_box_returns_false(void);
void test_first_focus_null_scene_returns_neg1(void);
void test_first_focus_empty_scene_returns_neg1(void);
void test_first_focus_single_button(void);
void test_first_focus_picks_top_left(void);
void test_first_focus_no_focusables_returns_neg1(void);
void test_first_focus_same_y_picks_leftmost(void);
void test_cycle_focus_forward(void);
void test_cycle_focus_backward(void);
void test_cycle_focus_wraps_forward(void);
void test_cycle_focus_wraps_backward(void);
void test_cycle_focus_invalid_current_returns_first(void);
void test_cycle_focus_null_scene_returns_neg1(void);
void test_cycle_focus_skips_non_focusable(void);
void test_cycle_focus_single_widget_stays(void);
void test_move_focus_down_beam(void);
void test_move_focus_up_beam(void);
void test_move_focus_right_beam(void);
void test_move_focus_left_beam(void);
void test_move_focus_loose_fallback_diagonal(void);
void test_move_focus_no_candidate_wraps(void);
void test_move_focus_2x2_grid(void);
void test_move_focus_null_scene_returns_neg1(void);
void test_move_focus_invalid_current_returns_first(void);
void test_move_focus_beam_prefers_closer(void);
void test_first_focus_in_rect_null_scene(void);
void test_move_focus_in_rect_null_scene(void);
void test_first_focus_in_rect_empty_rect_returns_neg1(void);
void test_cycle_focus_delta_zero_stays(void);
void test_move_focus_in_rect_right(void);
void test_move_focus_in_rect_left(void);
void test_move_focus_in_rect_up(void);
void test_move_focus_in_rect_down(void);
void test_move_focus_in_rect_wraps_forward(void);
void test_move_focus_in_rect_wraps_backward(void);
void test_move_focus_in_rect_excludes_outside(void);
void test_move_focus_left_wraps(void);
void test_move_focus_right_wraps(void);
void test_move_focus_invalid_dir_above_range(void);
void test_move_focus_invalid_dir_negative(void);

void app_main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_ui_nav_first_focus_in_rect_filters);
    RUN_TEST(test_ui_nav_move_focus_in_rect_cycles_inside_bounds);
    RUN_TEST(test_ui_nav_move_focus_in_rect_from_outside_picks_first);
    RUN_TEST(test_is_focusable_null_returns_false);
    RUN_TEST(test_is_focusable_button_returns_true);
    RUN_TEST(test_is_focusable_label_returns_false);
    RUN_TEST(test_is_focusable_checkbox_returns_true);
    RUN_TEST(test_is_focusable_radiobutton_returns_true);
    RUN_TEST(test_is_focusable_slider_returns_true);
    RUN_TEST(test_is_focusable_invisible_button_returns_false);
    RUN_TEST(test_is_focusable_disabled_button_returns_false);
    RUN_TEST(test_is_focusable_panel_returns_false);
    RUN_TEST(test_is_focusable_box_returns_false);
    RUN_TEST(test_first_focus_null_scene_returns_neg1);
    RUN_TEST(test_first_focus_empty_scene_returns_neg1);
    RUN_TEST(test_first_focus_single_button);
    RUN_TEST(test_first_focus_picks_top_left);
    RUN_TEST(test_first_focus_no_focusables_returns_neg1);
    RUN_TEST(test_first_focus_same_y_picks_leftmost);
    RUN_TEST(test_cycle_focus_forward);
    RUN_TEST(test_cycle_focus_backward);
    RUN_TEST(test_cycle_focus_wraps_forward);
    RUN_TEST(test_cycle_focus_wraps_backward);
    RUN_TEST(test_cycle_focus_invalid_current_returns_first);
    RUN_TEST(test_cycle_focus_null_scene_returns_neg1);
    RUN_TEST(test_cycle_focus_skips_non_focusable);
    RUN_TEST(test_cycle_focus_single_widget_stays);
    RUN_TEST(test_move_focus_down_beam);
    RUN_TEST(test_move_focus_up_beam);
    RUN_TEST(test_move_focus_right_beam);
    RUN_TEST(test_move_focus_left_beam);
    RUN_TEST(test_move_focus_loose_fallback_diagonal);
    RUN_TEST(test_move_focus_no_candidate_wraps);
    RUN_TEST(test_move_focus_2x2_grid);
    RUN_TEST(test_move_focus_null_scene_returns_neg1);
    RUN_TEST(test_move_focus_invalid_current_returns_first);
    RUN_TEST(test_move_focus_beam_prefers_closer);
    RUN_TEST(test_first_focus_in_rect_null_scene);
    RUN_TEST(test_move_focus_in_rect_null_scene);
    RUN_TEST(test_first_focus_in_rect_empty_rect_returns_neg1);
    RUN_TEST(test_cycle_focus_delta_zero_stays);
    RUN_TEST(test_move_focus_in_rect_right);
    RUN_TEST(test_move_focus_in_rect_left);
    RUN_TEST(test_move_focus_in_rect_up);
    RUN_TEST(test_move_focus_in_rect_down);
    RUN_TEST(test_move_focus_in_rect_wraps_forward);
    RUN_TEST(test_move_focus_in_rect_wraps_backward);
    RUN_TEST(test_move_focus_in_rect_excludes_outside);
    RUN_TEST(test_move_focus_left_wraps);
    RUN_TEST(test_move_focus_right_wraps);
    RUN_TEST(test_move_focus_invalid_dir_above_range);
    RUN_TEST(test_move_focus_invalid_dir_negative);
    UNITY_END();
}

#else

void test_ui_nav_first_focus_in_rect_filters(void);
void test_ui_nav_move_focus_in_rect_cycles_inside_bounds(void);
void test_ui_nav_move_focus_in_rect_from_outside_picks_first(void);
void test_is_focusable_null_returns_false(void);
void test_is_focusable_button_returns_true(void);
void test_is_focusable_label_returns_false(void);
void test_is_focusable_checkbox_returns_true(void);
void test_is_focusable_radiobutton_returns_true(void);
void test_is_focusable_slider_returns_true(void);
void test_is_focusable_invisible_button_returns_false(void);
void test_is_focusable_disabled_button_returns_false(void);
void test_is_focusable_panel_returns_false(void);
void test_is_focusable_box_returns_false(void);
void test_first_focus_null_scene_returns_neg1(void);
void test_first_focus_empty_scene_returns_neg1(void);
void test_first_focus_single_button(void);
void test_first_focus_picks_top_left(void);
void test_first_focus_no_focusables_returns_neg1(void);
void test_first_focus_same_y_picks_leftmost(void);
void test_cycle_focus_forward(void);
void test_cycle_focus_backward(void);
void test_cycle_focus_wraps_forward(void);
void test_cycle_focus_wraps_backward(void);
void test_cycle_focus_invalid_current_returns_first(void);
void test_cycle_focus_null_scene_returns_neg1(void);
void test_cycle_focus_skips_non_focusable(void);
void test_cycle_focus_single_widget_stays(void);
void test_move_focus_down_beam(void);
void test_move_focus_up_beam(void);
void test_move_focus_right_beam(void);
void test_move_focus_left_beam(void);
void test_move_focus_loose_fallback_diagonal(void);
void test_move_focus_no_candidate_wraps(void);
void test_move_focus_2x2_grid(void);
void test_move_focus_null_scene_returns_neg1(void);
void test_move_focus_invalid_current_returns_first(void);
void test_move_focus_beam_prefers_closer(void);
void test_first_focus_in_rect_null_scene(void);
void test_move_focus_in_rect_null_scene(void);
void test_first_focus_in_rect_empty_rect_returns_neg1(void);
void test_cycle_focus_delta_zero_stays(void);
void test_move_focus_in_rect_right(void);
void test_move_focus_in_rect_left(void);
void test_move_focus_in_rect_up(void);
void test_move_focus_in_rect_down(void);
void test_move_focus_in_rect_wraps_forward(void);
void test_move_focus_in_rect_wraps_backward(void);
void test_move_focus_in_rect_excludes_outside(void);
void test_move_focus_left_wraps(void);
void test_move_focus_right_wraps(void);
void test_move_focus_invalid_dir_above_range(void);
void test_move_focus_invalid_dir_negative(void);

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_ui_nav_first_focus_in_rect_filters);
    RUN_TEST(test_ui_nav_move_focus_in_rect_cycles_inside_bounds);
    RUN_TEST(test_ui_nav_move_focus_in_rect_from_outside_picks_first);
    RUN_TEST(test_is_focusable_null_returns_false);
    RUN_TEST(test_is_focusable_button_returns_true);
    RUN_TEST(test_is_focusable_label_returns_false);
    RUN_TEST(test_is_focusable_checkbox_returns_true);
    RUN_TEST(test_is_focusable_radiobutton_returns_true);
    RUN_TEST(test_is_focusable_slider_returns_true);
    RUN_TEST(test_is_focusable_invisible_button_returns_false);
    RUN_TEST(test_is_focusable_disabled_button_returns_false);
    RUN_TEST(test_is_focusable_panel_returns_false);
    RUN_TEST(test_is_focusable_box_returns_false);
    RUN_TEST(test_first_focus_null_scene_returns_neg1);
    RUN_TEST(test_first_focus_empty_scene_returns_neg1);
    RUN_TEST(test_first_focus_single_button);
    RUN_TEST(test_first_focus_picks_top_left);
    RUN_TEST(test_first_focus_no_focusables_returns_neg1);
    RUN_TEST(test_first_focus_same_y_picks_leftmost);
    RUN_TEST(test_cycle_focus_forward);
    RUN_TEST(test_cycle_focus_backward);
    RUN_TEST(test_cycle_focus_wraps_forward);
    RUN_TEST(test_cycle_focus_wraps_backward);
    RUN_TEST(test_cycle_focus_invalid_current_returns_first);
    RUN_TEST(test_cycle_focus_null_scene_returns_neg1);
    RUN_TEST(test_cycle_focus_skips_non_focusable);
    RUN_TEST(test_cycle_focus_single_widget_stays);
    RUN_TEST(test_move_focus_down_beam);
    RUN_TEST(test_move_focus_up_beam);
    RUN_TEST(test_move_focus_right_beam);
    RUN_TEST(test_move_focus_left_beam);
    RUN_TEST(test_move_focus_loose_fallback_diagonal);
    RUN_TEST(test_move_focus_no_candidate_wraps);
    RUN_TEST(test_move_focus_2x2_grid);
    RUN_TEST(test_move_focus_null_scene_returns_neg1);
    RUN_TEST(test_move_focus_invalid_current_returns_first);
    RUN_TEST(test_move_focus_beam_prefers_closer);
    RUN_TEST(test_first_focus_in_rect_null_scene);
    RUN_TEST(test_move_focus_in_rect_null_scene);
    RUN_TEST(test_first_focus_in_rect_empty_rect_returns_neg1);
    RUN_TEST(test_cycle_focus_delta_zero_stays);
    RUN_TEST(test_move_focus_in_rect_right);
    RUN_TEST(test_move_focus_in_rect_left);
    RUN_TEST(test_move_focus_in_rect_up);
    RUN_TEST(test_move_focus_in_rect_down);
    RUN_TEST(test_move_focus_in_rect_wraps_forward);
    RUN_TEST(test_move_focus_in_rect_wraps_backward);
    RUN_TEST(test_move_focus_in_rect_excludes_outside);
    RUN_TEST(test_move_focus_left_wraps);
    RUN_TEST(test_move_focus_right_wraps);
    RUN_TEST(test_move_focus_invalid_dir_above_range);
    RUN_TEST(test_move_focus_invalid_dir_negative);
    return UNITY_END();
}

#endif

