"""Generate firmware C++ theme headers from the single-source tools/m5_theme.json.

Safety: this only emits compile-time `constexpr` display constants (colours + layout).
Every name/value is allow-list validated before it is written as a C++ token, so a
malformed m5_theme.json can never inject arbitrary code into the firmware headers.

Usage:
  python tools/gen_firmware_theme.py           # regenerate headers (write-if-changed)
  python tools/gen_firmware_theme.py --check    # exit 1 if any header is out of date
"""

import json
import re
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
THEME_PATH = SCRIPT_DIR / "m5_theme.json"
OUTPUT_PATH = SCRIPT_DIR.parent / "firmware" / "din-rx" / "src" / "ui_theme_generated.h"
DIAL_OUTPUT_PATH = (
    SCRIPT_DIR.parent / "firmware" / "dial-tx" / "main" / "apps"
    / "app_prop_tx" / "gui" / "ui_theme_dial_generated.h"
)

# Dial colour names that differ between harness (canonical) and firmware. Everything
# else maps to itself, so adding a same-named colour needs NO entry here.
DIAL_NAME_EXCEPTIONS = {"WHITE": "COL_WHITE", "ACCENT": "SEL_ACCENT"}

_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_COLOR_RE = re.compile(r"^0x[0-9A-Fa-f]{6}$")


def _check_name(name: str) -> str:
    """Reject anything that is not a plain C identifier (safety: no token injection)."""
    if not isinstance(name, str) or not _NAME_RE.match(name):
        raise ValueError(f"invalid C identifier in m5_theme.json: {name!r}")
    return name


def _check_color(value: str) -> str:
    if not isinstance(value, str) or not _COLOR_RE.match(value):
        raise ValueError(f"invalid colour literal (want 0xRRGGBB): {value!r}")
    return value


def _check_int(value) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"invalid integer layout value: {value!r}")
    return value


def generate() -> str:
    """DinMeter firmware theme header (ui_theme_generated.h)."""
    theme = json.loads(THEME_PATH.read_text(encoding="utf-8"))
    lines = [
        "// AUTO-GENERATED by tools/gen_firmware_theme.py from tools/m5_theme.json -- DO NOT EDIT.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "// Colours (0xRRGGBB)",
    ]
    # json.load preserves object insertion order, matching the source file.
    for name, value in theme["colors"].items():
        lines.append(f"constexpr std::uint32_t {_check_name(name)} = {_check_color(value)};")
    lines.extend(["", "// Layout / geometry (px)"])
    for name, value in theme["layout"].items():
        lines.append(f"constexpr int {_check_name(name)} = {_check_int(value)};")
    return "\n".join(lines) + "\n"


def generate_dial() -> str:
    """M5 Dial firmware theme header; names match gui_prop_tx.cpp via the exceptions map."""
    theme = json.loads(THEME_PATH.read_text(encoding="utf-8"))
    dial = theme.get("dial", {})
    lines = [
        "// AUTO-GENERATED by tools/gen_firmware_theme.py from tools/m5_theme.json -- DO NOT EDIT.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "// M5 Dial theme colours (0xRRGGBB); names match gui_prop_tx.cpp.",
    ]
    for name, value in dial.items():
        fw_name = DIAL_NAME_EXCEPTIONS.get(name, name)
        lines.append(f"constexpr std::uint32_t {_check_name(fw_name)} = {_check_color(value)};")
    return "\n".join(lines) + "\n"


_TARGETS = ((OUTPUT_PATH, generate), (DIAL_OUTPUT_PATH, generate_dial))


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    check_only = "--check" in argv
    drift = False
    for path, build in _TARGETS:
        content = build()
        current = path.read_text(encoding="utf-8") if path.exists() else None
        label = path.name
        if current == content:
            print(f"{label}: unchanged")
            continue
        drift = True
        if check_only:
            print(f"{label}: OUT OF DATE -- run: python tools/gen_firmware_theme.py")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"{label}: written")
    return 1 if (check_only and drift) else 0


if __name__ == "__main__":
    sys.exit(main())
