"""Generate a LovyanGFX-compatible VLW (anti-aliased) font from a TTF, for the M5 DinMeter
Czech UI. Outputs build/fonts/<name>.vlw (binary) + <name>.h (PROGMEM C array for
canvas->loadFont(array)) and a <name>_preview.png rendered from the GENERATED data so the
font can be verified device-free.

VLW binary format (big-endian) — matches LovyanGFX 1.1.12 VLWfont::loadFont:
  header 24B : gCount, version(=11), yAdvance(=ascent+descent), reserved(0), ascent, descent
  per glyph 28B (sorted by codepoint): unicode, height, width, xAdvance, dY, dX, unused(0)
              dY = pixels from baseline up to the top of the glyph ink
              dX = left side bearing (pen -> glyph left)
  bitmaps    : after the table, each glyph's width*height 8-bit grayscale, same order.

Usage:
  python tools/make_vlw.py <ttf> <px> <name> [--preview "sample text"]
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "build" / "fonts"

# Czech diacritics (both cases) on top of ASCII printable 0x20..0x7E.
CZECH = "áéíóúýčďěňřšťůž"


def charset() -> list[str]:
    chars = [chr(c) for c in range(0x20, 0x7F)]
    chars += list(CZECH) + list(CZECH.upper())
    return sorted(set(chars), key=ord)


def build_vlw(ttf: Path, px: int) -> bytes:
    font = ImageFont.truetype(str(ttf), px)
    ascent, descent = font.getmetrics()
    glyph_meta: list[tuple[int, int, int, int, int, int]] = []
    bitmaps: list[bytes] = []

    for ch in charset():
        left, top, right, bottom = font.getbbox(ch)   # default anchor 'la' (ascender-top origin)
        w, h = right - left, bottom - top
        xadv = round(font.getlength(ch))
        if w > 0 and h > 0:
            img = Image.new("L", (w, h), 0)
            # Shift the ink box to (0,0): draw the glyph at (-left, -top).
            ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255)
            data = img.tobytes()                       # row-major, len == w*h
        else:
            w = h = 0
            data = b""
        d_x = left                                     # left side bearing
        d_y = ascent - top                             # baseline -> top of ink
        glyph_meta.append((ord(ch), h, w, xadv, d_y, d_x))
        bitmaps.append(data)

    out = bytearray()
    out += struct.pack(">6I", len(glyph_meta), 11, ascent + descent, 0, ascent, descent)
    for uni, h, w, xadv, d_y, d_x in glyph_meta:       # signed pack -> two's-complement for dY/dX<0
        out += struct.pack(">7i", uni, h, w, xadv, d_y, d_x, 0)
    for data in bitmaps:
        out += data
    return bytes(out)


def to_c_header(vlw: bytes, name: str) -> str:
    lines = [
        f"// Auto-generated VLW font '{name}' (anti-aliased, ASCII + Czech) for LovyanGFX.",
        "// Generated by tools/make_vlw.py -- do not edit by hand.",
        "#pragma once",
        "#include <cstdint>",
        "",
        f"const uint8_t {name}[] = {{",
    ]
    for i in range(0, len(vlw), 16):
        chunk = vlw[i:i + 16]
        lines.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append(f"const uint32_t {name}_len = {len(vlw)};")
    lines.append("")
    return "\n".join(lines)


def parse_vlw(vlw: bytes) -> tuple[dict, int, int]:
    """Parse a VLW exactly as LovyanGFX would, for device-free verification."""
    g_count, _ver, _yadv, _res, ascent, descent = struct.unpack(">6I", vlw[:24])
    table = []
    off = 24
    for _ in range(g_count):
        uni, h, w, xadv, d_y, d_x, _u = struct.unpack(">7i", vlw[off:off + 28])
        off += 28
        table.append((uni, h, w, xadv, d_y, d_x))
    glyphs = {}
    pos = 24 + g_count * 28
    for uni, h, w, xadv, d_y, d_x in table:
        n = w * h
        glyphs[uni] = (w, h, xadv, d_y, d_x, vlw[pos:pos + n])
        pos += n
    return glyphs, ascent, descent


def render_sample(vlw: bytes, text: str) -> Image.Image:
    """Render `text` from the GENERATED VLW, mimicking LovyanGFX placement (baseline=ascent,
    glyph top-left at (x+dX, ascent-dY), advance by xAdvance). White ink on the UI background."""
    glyphs, ascent, descent = parse_vlw(vlw)
    width = sum(glyphs.get(ord(c), (0, 0, 0, 0, 0, b""))[2] for c in text) + 8
    img = Image.new("RGB", (max(width, 16), ascent + descent + 8), (18, 24, 32))
    x = 4
    for c in text:
        g = glyphs.get(ord(c))
        if g is None:
            continue
        w, h, xadv, d_y, d_x, data = g
        if w > 0 and h > 0 and len(data) == w * h:
            mask = Image.frombytes("L", (w, h), data)
            ink = Image.new("RGB", (w, h), (231, 233, 237))
            img.paste(ink, (x + d_x, ascent - d_y + 4), mask)
        x += xadv
    return img


def main() -> int:
    if len(sys.argv) < 4:
        print("usage: python tools/make_vlw.py <ttf> <px> <name> [--preview \"text\"]")
        return 2
    ttf = Path(sys.argv[1])
    if not ttf.is_absolute():
        ttf = ROOT / ttf
    px = int(sys.argv[2])
    name = sys.argv[3]
    sample = "PÁLÍ NABITO ZAJIŠTĚNO PŘECHOD CELKOVÁ DOBA 1.2s 80% náhled"
    if "--preview" in sys.argv:
        i = sys.argv.index("--preview")
        if i + 1 < len(sys.argv):
            sample = sys.argv[i + 1]

    if not ttf.exists():
        print(f"TTF not found: {ttf}")
        return 2

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    vlw = build_vlw(ttf, px)
    (OUT_DIR / f"{name}.vlw").write_bytes(vlw)
    (OUT_DIR / f"{name}.h").write_text(to_c_header(vlw, name), encoding="utf-8")
    render_sample(vlw, sample).save(OUT_DIR / f"{name}_preview.png")

    glyphs, ascent, descent = parse_vlw(vlw)
    print(f"{name}: {len(charset())} glyphs, {len(vlw)} bytes, ascent={ascent} descent={descent} "
          f"(px={px}, ttf={ttf.name})")
    print(f"  -> {OUT_DIR / (name + '.vlw')}")
    print(f"  -> {OUT_DIR / (name + '.h')}  (loadFont array)")
    print(f"  -> {OUT_DIR / (name + '_preview.png')}  (rendered FROM the generated VLW)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
