# Auto-generated by UI Designer
# Scene: showcase
# Generated: 2025-11-16 22:03:30

from dataclasses import dataclass
from typing import List


@dataclass
class Widget:
    type: str
    x: int
    y: int
    width: int
    height: int
    text: str = ''
    style: str = 'default'
    color_fg: str = 'white'
    color_bg: str = 'black'
    border: bool = True
    align: str = 'left'


def create_showcase_scene() -> List[Widget]:
    """Create showcase scene widgets"""
    return [
        Widget(
            type='label',
            x=4,
            y=0,
            width=24,
            height=1,
            text='Title Label',
            style='bold',
            border=False,
        ),
        Widget(
            type='textbox',
            x=32,
            y=0,
            width=24,
            height=3,
            text='Text input',
        ),
        Widget(
            type='button',
            x=4,
            y=8,
            width=16,
            height=5,
            text='OK',
            color_fg='black',
            color_bg='green',
            align='center',
        ),
        Widget(
            type='box',
            x=24,
            y=8,
            width=16,
            height=5,
            text='Info Box',
        ),
        Widget(
            type='panel',
            x=44,
            y=8,
            width=20,
            height=5,
            text='Status',
            color_bg='blue',
        ),
        Widget(
            type='progressbar',
            x=4,
            y=16,
            width=30,
            height=2,
            color_fg='green',
        ),
        Widget(
            type='gauge',
            x=38,
            y=16,
            width=12,
            height=8,
            color_fg='yellow',
        ),
        Widget(
            type='slider',
            x=56,
            y=16,
            width=24,
            height=1,
        ),
        Widget(
            type='checkbox',
            x=4,
            y=23,
            width=20,
            height=1,
            text='Enable WiFi',
        ),
        Widget(
            type='radiobutton',
            x=30,
            y=23,
            width=20,
            height=1,
            text='Option A',
        ),
        Widget(
            type='icon',
            x=4,
            y=28,
            width=4,
            height=4,
            color_fg='yellow',
        ),
        Widget(
            type='chart',
            x=14,
            y=28,
            width=20,
            height=10,
            color_fg='cyan',
        ),
    ]


if __name__ == '__main__':
    widgets = create_showcase_scene()
    print(f'Created {len(widgets)} widgets for showcase scene')