// AUTO-GENERATED by tools/gen_firmware_theme.py from tools/m5_theme.json -- DO NOT EDIT.
#pragma once
#include <cstdint>

// M5 Dial theme colours (0xRRGGBB); names match gui_prop_tx.cpp.
constexpr std::uint32_t P_GREEN = 0x3FB36B;
constexpr std::uint32_t P_AMBER = 0xFF8C00;
constexpr std::uint32_t P_RED = 0xCC0000;
constexpr std::uint32_t COL_WHITE = 0xFFFFFF;
constexpr std::uint32_t BG_BASE = 0x14171D;
constexpr std::uint32_t RING_TRK = 0x363D4A;
constexpr std::uint32_t SOCKET = 0x0B0D11;
constexpr std::uint32_t TEXT_HI = 0xE7E9ED;
constexpr std::uint32_t TEXT_DIM = 0x767D89;
constexpr std::uint32_t SEL_ACCENT = 0xF5F7FA;
constexpr std::uint32_t MODE_SETUP = 0x59C6DC;
