#ifndef UI_ANIMATIONS_H
#define UI_ANIMATIONS_H

#include <stdint.h>
#include <stdbool.h>

/* Auto-generated animation structures */
/* DO NOT EDIT - Generated by animation_export_c.py */

/* Animation types */
typedef enum {
    UI_ANIM_BOUNCE = 0,
    UI_ANIM_FADE = 1,
    UI_ANIM_MOVE = 2,
    UI_ANIM_OPACITY = 3,
    UI_ANIM_PULSE = 4,
    UI_ANIM_SHAKE = 5,
    UI_ANIM_SLIDE_LEFT = 6,
    UI_ANIM_ZOOM_IN = 7,
} ui_animation_type_t;

/* Easing functions */
typedef enum {
    UI_EASING_EASE_IN = 0,
    UI_EASING_EASE_IN_OUT = 1,
    UI_EASING_EASE_OUT = 2,
    UI_EASING_EASE_OUT_BOUNCE = 3,
    UI_EASING_EASE_OUT_CUBIC = 4,
    UI_EASING_LINEAR = 5,
} ui_easing_t;

/* Keyframe structure */
typedef struct {
    float time;           /* 0.0 to 1.0 */
    int16_t x;            /* Position X (or -1 if unused) */
    int16_t y;            /* Position Y (or -1 if unused) */
    uint16_t width;       /* Width (or 0 if unused) */
    uint16_t height;      /* Height (or 0 if unused) */
    uint8_t opacity;      /* 0-255 (or 255 if unused) */
    uint16_t color;       /* RGB565 (or 0 if unused) */
    ui_easing_t easing;   /* Easing to next keyframe */
} ui_keyframe_t;

/* Animation structure */
typedef struct {
    const char *name;
    ui_animation_type_t type;
    uint16_t duration_ms;
    uint16_t delay_ms;
    int16_t iterations;        /* -1 for infinite */
    ui_easing_t easing;
    const ui_keyframe_t *keyframes;
    uint8_t keyframe_count;
} ui_animation_t;

/* Animation player state */
typedef struct {
    const ui_animation_t *animation;
    uint32_t start_time_ms;
    int16_t current_iteration;
    bool is_playing;
} ui_animation_player_t;

/* Exported animations */
extern const ui_animation_t anim_fadein;
extern const ui_animation_t anim_slideinleft;
extern const ui_animation_t anim_bounce;
extern const ui_animation_t anim_pulse;
extern const ui_animation_t anim_shake;
extern const ui_animation_t anim_zoomin;
extern const ui_animation_t anim_fade_in;
extern const ui_animation_t anim_slide_fade;
extern const ui_animation_t anim_bounce;
extern const ui_animation_t anim_pulse;
extern const ui_animation_t anim_complex_path;

/* Animation player API */
void ui_animation_player_init(ui_animation_player_t *player);
void ui_animation_player_start(ui_animation_player_t *player, const ui_animation_t *anim, uint32_t current_time_ms);
void ui_animation_player_stop(ui_animation_player_t *player);
bool ui_animation_player_update(ui_animation_player_t *player, uint32_t current_time_ms);
float ui_animation_player_get_progress(ui_animation_player_t *player, uint32_t current_time_ms);

/* Easing function evaluator */
float ui_easing_evaluate(ui_easing_t easing, float t);

#endif /* UI_ANIMATIONS_H */
