#include "ui_animations.h"
#include <string.h>

/* Auto-generated animation data */
/* DO NOT EDIT - Generated by animation_export_c.py */

/* Keyframes for Pulse */
static const ui_keyframe_t keyframes_pulse[] = {
    {0.0f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.5f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {1.0f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
};

/* Keyframes for Shake */
static const ui_keyframe_t keyframes_shake[] = {
    {0.0f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.1f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.2f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.3f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.4f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.5f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.6f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.7f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.8f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.9f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
    {1.0f, -1, -1, 0, 0, 255, 0, UI_EASING_LINEAR},
};

/* Keyframes for ZoomIn */
static const ui_keyframe_t keyframes_zoomin[] = {
    {0.0f, -1, -1, 0, 0, 0, 0, UI_EASING_LINEAR},
    {1.0f, -1, -1, 0, 0, 100, 0, UI_EASING_LINEAR},
};

/* Keyframes for fade_in */
static const ui_keyframe_t keyframes_fade_in[] = {
    {0.0f, -1, -1, 0, 0, 0.0, 0, UI_EASING_LINEAR},
    {1.0f, -1, -1, 0, 0, 1.0, 0, UI_EASING_LINEAR},
};

/* Keyframes for slide_fade */
static const ui_keyframe_t keyframes_slide_fade[] = {
    {0.0f, -100, -1, 0, 0, 0.0, 0, UI_EASING_EASE_OUT},
    {0.5f, -20, -1, 0, 0, 0.5, 0, UI_EASING_EASE_OUT},
    {1.0f, 0, -1, 0, 0, 1.0, 0, UI_EASING_LINEAR},
};

/* Keyframes for bounce */
static const ui_keyframe_t keyframes_bounce[] = {
    {0.0f, -1, 0, 0, 0, 255, 0, UI_EASING_EASE_OUT_BOUNCE},
    {0.5f, -1, 50, 0, 0, 255, 0, UI_EASING_EASE_IN},
    {1.0f, -1, 0, 0, 0, 255, 0, UI_EASING_EASE_OUT_BOUNCE},
};

/* Keyframes for pulse */
static const ui_keyframe_t keyframes_pulse[] = {
    {0.0f, -1, -1, 0, 0, 1.0, 0, UI_EASING_EASE_IN_OUT},
    {0.5f, -1, -1, 0, 0, 0.8, 0, UI_EASING_EASE_IN_OUT},
    {1.0f, -1, -1, 0, 0, 1.0, 0, UI_EASING_EASE_IN_OUT},
};

/* Keyframes for complex_path */
static const ui_keyframe_t keyframes_complex_path[] = {
    {0.0f, 0, 0, 0, 0, 255, 0, UI_EASING_LINEAR},
    {0.25f, 100, 0, 0, 0, 255, 0, UI_EASING_EASE_IN},
    {0.5f, 100, 100, 0, 0, 255, 0, UI_EASING_EASE_OUT},
    {0.75f, 0, 100, 0, 0, 255, 0, UI_EASING_EASE_IN},
    {1.0f, 0, 0, 0, 0, 255, 0, UI_EASING_EASE_OUT},
};

/* Animation: FadeIn */
const ui_animation_t anim_fadein = {
    .name = "FadeIn",
    .type = UI_ANIM_OPACITY,
    .duration_ms = 500,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_EASE_IN,
    .keyframes = NULL,
    .keyframe_count = 0
};

/* Animation: SlideInLeft */
const ui_animation_t anim_slideinleft = {
    .name = "SlideInLeft",
    .type = UI_ANIM_SLIDE_LEFT,
    .duration_ms = 400,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_EASE_OUT_CUBIC,
    .keyframes = NULL,
    .keyframe_count = 0
};

/* Animation: Bounce */
const ui_animation_t anim_bounce = {
    .name = "Bounce",
    .type = UI_ANIM_BOUNCE,
    .duration_ms = 600,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_EASE_OUT_BOUNCE,
    .keyframes = NULL,
    .keyframe_count = 0
};

/* Animation: Pulse */
const ui_animation_t anim_pulse = {
    .name = "Pulse",
    .type = UI_ANIM_PULSE,
    .duration_ms = 800,
    .delay_ms = 0,
    .iterations = -1,
    .easing = UI_EASING_EASE_IN_OUT,
    .keyframes = keyframes_pulse,
    .keyframe_count = 3
};

/* Animation: Shake */
const ui_animation_t anim_shake = {
    .name = "Shake",
    .type = UI_ANIM_SHAKE,
    .duration_ms = 500,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_LINEAR,
    .keyframes = keyframes_shake,
    .keyframe_count = 11
};

/* Animation: ZoomIn */
const ui_animation_t anim_zoomin = {
    .name = "ZoomIn",
    .type = UI_ANIM_ZOOM_IN,
    .duration_ms = 400,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_EASE_OUT_CUBIC,
    .keyframes = keyframes_zoomin,
    .keyframe_count = 2
};

/* Animation: fade_in */
const ui_animation_t anim_fade_in = {
    .name = "fade_in",
    .type = UI_ANIM_FADE,
    .duration_ms = 500,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_EASE_IN_OUT,
    .keyframes = keyframes_fade_in,
    .keyframe_count = 2
};

/* Animation: slide_fade */
const ui_animation_t anim_slide_fade = {
    .name = "slide_fade",
    .type = UI_ANIM_SLIDE_LEFT,
    .duration_ms = 800,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_EASE_OUT,
    .keyframes = keyframes_slide_fade,
    .keyframe_count = 3
};

/* Animation: bounce */
const ui_animation_t anim_bounce = {
    .name = "bounce",
    .type = UI_ANIM_BOUNCE,
    .duration_ms = 1200,
    .delay_ms = 0,
    .iterations = -1,
    .easing = UI_EASING_EASE_OUT_BOUNCE,
    .keyframes = keyframes_bounce,
    .keyframe_count = 3
};

/* Animation: pulse */
const ui_animation_t anim_pulse = {
    .name = "pulse",
    .type = UI_ANIM_PULSE,
    .duration_ms = 1000,
    .delay_ms = 0,
    .iterations = -1,
    .easing = UI_EASING_EASE_IN_OUT,
    .keyframes = keyframes_pulse,
    .keyframe_count = 3
};

/* Animation: complex_path */
const ui_animation_t anim_complex_path = {
    .name = "complex_path",
    .type = UI_ANIM_MOVE,
    .duration_ms = 2000,
    .delay_ms = 0,
    .iterations = 1,
    .easing = UI_EASING_LINEAR,
    .keyframes = keyframes_complex_path,
    .keyframe_count = 5
};

/* Easing function implementations */
float ui_easing_evaluate(ui_easing_t easing, float t) {
    switch (easing) {
        case UI_EASING_LINEAR:
            return t;
        
        case UI_EASING_EASE_IN:
            return t * t;
        
        case UI_EASING_EASE_OUT:
            return t * (2.0f - t);
        
        case UI_EASING_EASE_IN_OUT:
            return t * t * (3.0f - 2.0f * t);
        
        case UI_EASING_EASE_IN_QUAD:
            return t * t;
        
        case UI_EASING_EASE_OUT_QUAD:
            return t * (2.0f - t);
        
        default:
            return t;
    }
}

/* Animation player implementation */
void ui_animation_player_init(ui_animation_player_t *player) {
    memset(player, 0, sizeof(ui_animation_player_t));
}

void ui_animation_player_start(ui_animation_player_t *player, const ui_animation_t *anim, uint32_t current_time_ms) {
    player->animation = anim;
    player->start_time_ms = current_time_ms + anim->delay_ms;
    player->current_iteration = 0;
    player->is_playing = true;
}

void ui_animation_player_stop(ui_animation_player_t *player) {
    player->is_playing = false;
}

bool ui_animation_player_update(ui_animation_player_t *player, uint32_t current_time_ms) {
    if (!player->is_playing || !player->animation) {
        return false;
    }
    
    uint32_t elapsed = current_time_ms - player->start_time_ms;
    uint32_t duration = player->animation->duration_ms;
    
    if (elapsed >= duration) {
        player->current_iteration++;
        
        if (player->animation->iterations == -1) {
            /* Infinite loop */
            player->start_time_ms = current_time_ms;
            return true;
        } else if (player->current_iteration >= player->animation->iterations) {
            /* Animation finished */
            player->is_playing = false;
            return false;
        } else {
            /* Next iteration */
            player->start_time_ms = current_time_ms;
            return true;
        }
    }
    
    return true;
}

float ui_animation_player_get_progress(ui_animation_player_t *player, uint32_t current_time_ms) {
    if (!player->is_playing || !player->animation) {
        return 0.0f;
    }
    
    uint32_t elapsed = current_time_ms - player->start_time_ms;
    uint32_t duration = player->animation->duration_ms;
    
    if (duration == 0) {
        return 1.0f;
    }
    
    float t = (float)elapsed / (float)duration;
    if (t > 1.0f) {
        t = 1.0f;
    }
    
    return ui_easing_evaluate(player->animation->easing, t);
}
