#include "unity.h"

#ifdef ESP_PLATFORM

void test_render_widget_null_widget(void);
void test_render_widget_null_ops(void);
void test_render_scene_null_scene(void);
void test_render_scene_null_ops(void);
void test_render_scene_empty(void);
void test_render_invisible_widget_no_draw(void);
void test_render_widget_no_extended_fields_is_visible(void);
void test_render_label_draws_text(void);
void test_render_label_no_text_no_draw(void);
void test_render_label_empty_text_no_draw(void);
void test_render_box_draws_rect(void);
void test_render_button_draws_border_and_text(void);
void test_render_button_no_text_still_draws_border(void);
void test_render_progressbar_zero(void);
void test_render_progressbar_full(void);
void test_render_checkbox_unchecked(void);
void test_render_checkbox_checked(void);
void test_render_radiobutton_selected(void);
void test_render_gauge(void);
void test_render_slider(void);
void test_render_slider_at_min(void);
void test_render_slider_at_max(void);
void test_render_textbox_with_text(void);
void test_render_textbox_empty_text(void);
void test_render_panel(void);
void test_render_chart(void);
void test_render_scene_multiple_widgets(void);
void test_render_scene_skips_invisible(void);
void test_render_highlighted_widget_draws(void);
void test_render_inverse_widget_draws(void);
void test_render_disabled_widget_still_draws(void);
void test_render_box_border_none(void);
void test_render_box_border_double(void);
void test_render_unknown_type_draws_rect(void);
void test_render_with_minimal_ops(void);
void test_render_zero_size_label(void);
void test_render_progressbar_large_range_no_overflow(void);
void test_render_slider_large_range_no_overflow(void);
void test_render_gauge_large_range_no_overflow(void);
void test_render_chart_large_range_no_overflow(void);
void test_render_box_zero_width_no_crash(void);
void test_render_box_zero_height_no_crash(void);
void test_render_progressbar_tiny_no_crash(void);
void test_render_progressbar_inverted_range_no_crash(void);
void test_render_slider_inverted_range_no_crash(void);
void test_render_gauge_inverted_range_no_crash(void);
void test_render_checkbox_tiny_no_crash(void);

void app_main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_render_widget_null_widget);
    RUN_TEST(test_render_widget_null_ops);
    RUN_TEST(test_render_scene_null_scene);
    RUN_TEST(test_render_scene_null_ops);
    RUN_TEST(test_render_scene_empty);
    RUN_TEST(test_render_invisible_widget_no_draw);
    RUN_TEST(test_render_widget_no_extended_fields_is_visible);
    RUN_TEST(test_render_label_draws_text);
    RUN_TEST(test_render_label_no_text_no_draw);
    RUN_TEST(test_render_label_empty_text_no_draw);
    RUN_TEST(test_render_box_draws_rect);
    RUN_TEST(test_render_button_draws_border_and_text);
    RUN_TEST(test_render_button_no_text_still_draws_border);
    RUN_TEST(test_render_progressbar_zero);
    RUN_TEST(test_render_progressbar_full);
    RUN_TEST(test_render_checkbox_unchecked);
    RUN_TEST(test_render_checkbox_checked);
    RUN_TEST(test_render_radiobutton_selected);
    RUN_TEST(test_render_gauge);
    RUN_TEST(test_render_slider);
    RUN_TEST(test_render_slider_at_min);
    RUN_TEST(test_render_slider_at_max);
    RUN_TEST(test_render_textbox_with_text);
    RUN_TEST(test_render_textbox_empty_text);
    RUN_TEST(test_render_panel);
    RUN_TEST(test_render_chart);
    RUN_TEST(test_render_scene_multiple_widgets);
    RUN_TEST(test_render_scene_skips_invisible);
    RUN_TEST(test_render_highlighted_widget_draws);
    RUN_TEST(test_render_inverse_widget_draws);
    RUN_TEST(test_render_disabled_widget_still_draws);
    RUN_TEST(test_render_box_border_none);
    RUN_TEST(test_render_box_border_double);
    RUN_TEST(test_render_unknown_type_draws_rect);
    RUN_TEST(test_render_with_minimal_ops);
    RUN_TEST(test_render_zero_size_label);
    RUN_TEST(test_render_progressbar_large_range_no_overflow);
    RUN_TEST(test_render_slider_large_range_no_overflow);
    RUN_TEST(test_render_gauge_large_range_no_overflow);
    RUN_TEST(test_render_chart_large_range_no_overflow);
    RUN_TEST(test_render_box_zero_width_no_crash);
    RUN_TEST(test_render_box_zero_height_no_crash);
    RUN_TEST(test_render_progressbar_tiny_no_crash);
    RUN_TEST(test_render_progressbar_inverted_range_no_crash);
    RUN_TEST(test_render_slider_inverted_range_no_crash);
    RUN_TEST(test_render_gauge_inverted_range_no_crash);
    RUN_TEST(test_render_checkbox_tiny_no_crash);
    UNITY_END();
}

#else

void test_render_widget_null_widget(void);
void test_render_widget_null_ops(void);
void test_render_scene_null_scene(void);
void test_render_scene_null_ops(void);
void test_render_scene_empty(void);
void test_render_invisible_widget_no_draw(void);
void test_render_widget_no_extended_fields_is_visible(void);
void test_render_label_draws_text(void);
void test_render_label_no_text_no_draw(void);
void test_render_label_empty_text_no_draw(void);
void test_render_box_draws_rect(void);
void test_render_button_draws_border_and_text(void);
void test_render_button_no_text_still_draws_border(void);
void test_render_progressbar_zero(void);
void test_render_progressbar_full(void);
void test_render_checkbox_unchecked(void);
void test_render_checkbox_checked(void);
void test_render_radiobutton_selected(void);
void test_render_gauge(void);
void test_render_slider(void);
void test_render_slider_at_min(void);
void test_render_slider_at_max(void);
void test_render_textbox_with_text(void);
void test_render_textbox_empty_text(void);
void test_render_panel(void);
void test_render_chart(void);
void test_render_scene_multiple_widgets(void);
void test_render_scene_skips_invisible(void);
void test_render_highlighted_widget_draws(void);
void test_render_inverse_widget_draws(void);
void test_render_disabled_widget_still_draws(void);
void test_render_box_border_none(void);
void test_render_box_border_double(void);
void test_render_unknown_type_draws_rect(void);
void test_render_with_minimal_ops(void);
void test_render_zero_size_label(void);
void test_render_progressbar_large_range_no_overflow(void);
void test_render_slider_large_range_no_overflow(void);
void test_render_gauge_large_range_no_overflow(void);
void test_render_chart_large_range_no_overflow(void);
void test_render_box_zero_width_no_crash(void);
void test_render_box_zero_height_no_crash(void);
void test_render_progressbar_tiny_no_crash(void);
void test_render_progressbar_inverted_range_no_crash(void);
void test_render_slider_inverted_range_no_crash(void);
void test_render_gauge_inverted_range_no_crash(void);
void test_render_checkbox_tiny_no_crash(void);

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_render_widget_null_widget);
    RUN_TEST(test_render_widget_null_ops);
    RUN_TEST(test_render_scene_null_scene);
    RUN_TEST(test_render_scene_null_ops);
    RUN_TEST(test_render_scene_empty);
    RUN_TEST(test_render_invisible_widget_no_draw);
    RUN_TEST(test_render_widget_no_extended_fields_is_visible);
    RUN_TEST(test_render_label_draws_text);
    RUN_TEST(test_render_label_no_text_no_draw);
    RUN_TEST(test_render_label_empty_text_no_draw);
    RUN_TEST(test_render_box_draws_rect);
    RUN_TEST(test_render_button_draws_border_and_text);
    RUN_TEST(test_render_button_no_text_still_draws_border);
    RUN_TEST(test_render_progressbar_zero);
    RUN_TEST(test_render_progressbar_full);
    RUN_TEST(test_render_checkbox_unchecked);
    RUN_TEST(test_render_checkbox_checked);
    RUN_TEST(test_render_radiobutton_selected);
    RUN_TEST(test_render_gauge);
    RUN_TEST(test_render_slider);
    RUN_TEST(test_render_slider_at_min);
    RUN_TEST(test_render_slider_at_max);
    RUN_TEST(test_render_textbox_with_text);
    RUN_TEST(test_render_textbox_empty_text);
    RUN_TEST(test_render_panel);
    RUN_TEST(test_render_chart);
    RUN_TEST(test_render_scene_multiple_widgets);
    RUN_TEST(test_render_scene_skips_invisible);
    RUN_TEST(test_render_highlighted_widget_draws);
    RUN_TEST(test_render_inverse_widget_draws);
    RUN_TEST(test_render_disabled_widget_still_draws);
    RUN_TEST(test_render_box_border_none);
    RUN_TEST(test_render_box_border_double);
    RUN_TEST(test_render_unknown_type_draws_rect);
    RUN_TEST(test_render_with_minimal_ops);
    RUN_TEST(test_render_zero_size_label);
    RUN_TEST(test_render_progressbar_large_range_no_overflow);
    RUN_TEST(test_render_slider_large_range_no_overflow);
    RUN_TEST(test_render_gauge_large_range_no_overflow);
    RUN_TEST(test_render_chart_large_range_no_overflow);
    RUN_TEST(test_render_box_zero_width_no_crash);
    RUN_TEST(test_render_box_zero_height_no_crash);
    RUN_TEST(test_render_progressbar_tiny_no_crash);
    RUN_TEST(test_render_progressbar_inverted_range_no_crash);
    RUN_TEST(test_render_slider_inverted_range_no_crash);
    RUN_TEST(test_render_gauge_inverted_range_no_crash);
    RUN_TEST(test_render_checkbox_tiny_no_crash);
    UNITY_END();
    return 0;
}

#endif
