#!/usr/bin/env python3
"""
Animation Export to C Code for ESP32
Converts Animation objects to C structures for embedded use
"""

import json
from pathlib import Path
from typing import List

from ui_animations import Animation


class AnimationExporter:
    """Export animations to C code for ESP32"""
    
    def __init__(self):
        self.animations: List[Animation] = []
        self.header_guards = set()
    
    def add_animation(self, animation: Animation):
        """Add animation to export list"""
        self.animations.append(animation)
    
    def generate_header(self, filename: str = "ui_animations.h") -> str:
        """Generate C header file with animation declarations"""
        guard = filename.upper().replace(".", "_")
        self.header_guards.add(guard)
        
        lines = [
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "",
            "/* Auto-generated animation structures */",
            "/* DO NOT EDIT - Generated by animation_export_c.py */",
            "",
            "/* Animation types */",
            "typedef enum {",
        ]
        
        # Animation type enum
        types = set()
        for anim in self.animations:
            types.add(anim.type)
        
        for idx, anim_type in enumerate(sorted(types)):
            enum_name = f"UI_ANIM_{anim_type.upper()}"
            lines.append(f"    {enum_name} = {idx},")
        
        lines.extend([
            "} ui_animation_type_t;",
            "",
            "/* Easing functions */",
            "typedef enum {",
        ])
        
        # Easing function enum
        easings = set()
        for anim in self.animations:
            easings.add(anim.easing)
        
        for idx, easing in enumerate(sorted(easings)):
            enum_name = f"UI_EASING_{easing.upper()}"
            lines.append(f"    {enum_name} = {idx},")
        
        lines.extend([
            "} ui_easing_t;",
            "",
            "/* Keyframe structure */",
            "typedef struct {",
            "    float time;           /* 0.0 to 1.0 */",
            "    int16_t x;            /* Position X (or -1 if unused) */",
            "    int16_t y;            /* Position Y (or -1 if unused) */",
            "    uint16_t width;       /* Width (or 0 if unused) */",
            "    uint16_t height;      /* Height (or 0 if unused) */",
            "    uint8_t opacity;      /* 0-255 (or 255 if unused) */",
            "    uint16_t color;       /* RGB565 (or 0 if unused) */",
            "    ui_easing_t easing;   /* Easing to next keyframe */",
            "} ui_keyframe_t;",
            "",
            "/* Animation structure */",
            "typedef struct {",
            "    const char *name;",
            "    ui_animation_type_t type;",
            "    uint16_t duration_ms;",
            "    uint16_t delay_ms;",
            "    int16_t iterations;        /* -1 for infinite */",
            "    ui_easing_t easing;",
            "    const ui_keyframe_t *keyframes;",
            "    uint8_t keyframe_count;",
            "} ui_animation_t;",
            "",
            "/* Animation player state */",
            "typedef struct {",
            "    const ui_animation_t *animation;",
            "    uint32_t start_time_ms;",
            "    int16_t current_iteration;",
            "    bool is_playing;",
            "} ui_animation_player_t;",
            "",
            "/* Exported animations */",
        ])
        
        # Forward declarations
        for anim in self.animations:
            safe_name = self._sanitize_name(anim.name)
            lines.append(f"extern const ui_animation_t anim_{safe_name};")
        
        lines.extend([
            "",
            "/* Animation player API */",
            "void ui_animation_player_init(ui_animation_player_t *player);",
            "void ui_animation_player_start(ui_animation_player_t *player, const ui_animation_t *anim, uint32_t current_time_ms);",
            "void ui_animation_player_stop(ui_animation_player_t *player);",
            "bool ui_animation_player_update(ui_animation_player_t *player, uint32_t current_time_ms);",
            "float ui_animation_player_get_progress(ui_animation_player_t *player, uint32_t current_time_ms);",
            "",
            "/* Easing function evaluator */",
            "float ui_easing_evaluate(ui_easing_t easing, float t);",
            "",
            f"#endif /* {guard} */",
            ""
        ])
        
        return "\n".join(lines)
    
    def generate_implementation(self, filename: str = "ui_animations.c") -> str:
        """Generate C implementation file with animation data"""
        header = filename.replace(".c", ".h")
        
        lines = [
            f"#include \"{header}\"",
            "#include <string.h>",
            "",
            "/* Auto-generated animation data */",
            "/* DO NOT EDIT - Generated by animation_export_c.py */",
            "",
        ]
        
        # Generate keyframe arrays
        for anim in self.animations:
            if not anim.keyframes:
                continue
            
            safe_name = self._sanitize_name(anim.name)
            lines.append(f"/* Keyframes for {anim.name} */")
            lines.append(f"static const ui_keyframe_t keyframes_{safe_name}[] = {{")
            
            for kf in anim.keyframes:
                # Handle both Keyframe objects and dicts
                if isinstance(kf, dict):
                    time = kf.get('time', 0.0)
                    props = kf.get('properties', {})
                    easing = kf.get('easing', 'linear')
                else:
                    time = kf.time
                    props = kf.properties
                    easing = kf.easing
                
                x = props.get('x', -1)
                y = props.get('y', -1)
                width = props.get('width', 0)
                height = props.get('height', 0)
                opacity = props.get('opacity', 255)
                color = props.get('color', 0)
                
                easing_enum = f"UI_EASING_{easing.upper()}"
                
                lines.append(f"    {{{time}f, {x}, {y}, {width}, {height}, {opacity}, {color}, {easing_enum}}},")
            
            lines.append("};")
            lines.append("")
        
        # Generate animation structures
        for anim in self.animations:
            safe_name = self._sanitize_name(anim.name)
            type_enum = f"UI_ANIM_{anim.type.upper()}"
            easing_enum = f"UI_EASING_{anim.easing.upper()}"
            
            keyframes_ptr = f"keyframes_{safe_name}" if anim.keyframes else "NULL"
            keyframe_count = len(anim.keyframes)
            
            lines.extend([
                f"/* Animation: {anim.name} */",
                f"const ui_animation_t anim_{safe_name} = {{",
                f"    .name = \"{anim.name}\",",
                f"    .type = {type_enum},",
                f"    .duration_ms = {anim.duration},",
                f"    .delay_ms = {anim.delay},",
                f"    .iterations = {anim.iterations},",
                f"    .easing = {easing_enum},",
                f"    .keyframes = {keyframes_ptr},",
                f"    .keyframe_count = {keyframe_count}",
                "};",
                ""
            ])
        
        # Generate easing function evaluator
        lines.extend([
            "/* Easing function implementations */",
            "float ui_easing_evaluate(ui_easing_t easing, float t) {",
            "    switch (easing) {",
            "        case UI_EASING_LINEAR:",
            "            return t;",
            "        ",
            "        case UI_EASING_EASE_IN:",
            "            return t * t;",
            "        ",
            "        case UI_EASING_EASE_OUT:",
            "            return t * (2.0f - t);",
            "        ",
            "        case UI_EASING_EASE_IN_OUT:",
            "            return t * t * (3.0f - 2.0f * t);",
            "        ",
            "        case UI_EASING_EASE_IN_QUAD:",
            "            return t * t;",
            "        ",
            "        case UI_EASING_EASE_OUT_QUAD:",
            "            return t * (2.0f - t);",
            "        ",
            "        default:",
            "            return t;",
            "    }",
            "}",
            "",
        ])
        
        # Generate animation player functions
        lines.extend([
            "/* Animation player implementation */",
            "void ui_animation_player_init(ui_animation_player_t *player) {",
            "    memset(player, 0, sizeof(ui_animation_player_t));",
            "}",
            "",
            "void ui_animation_player_start(ui_animation_player_t *player, const ui_animation_t *anim, uint32_t current_time_ms) {",
            "    player->animation = anim;",
            "    player->start_time_ms = current_time_ms + anim->delay_ms;",
            "    player->current_iteration = 0;",
            "    player->is_playing = true;",
            "}",
            "",
            "void ui_animation_player_stop(ui_animation_player_t *player) {",
            "    player->is_playing = false;",
            "}",
            "",
            "bool ui_animation_player_update(ui_animation_player_t *player, uint32_t current_time_ms) {",
            "    if (!player->is_playing || !player->animation) {",
            "        return false;",
            "    }",
            "    ",
            "    uint32_t elapsed = current_time_ms - player->start_time_ms;",
            "    uint32_t duration = player->animation->duration_ms;",
            "    ",
            "    if (elapsed >= duration) {",
            "        player->current_iteration++;",
            "        ",
            "        if (player->animation->iterations == -1) {",
            "            /* Infinite loop */",
            "            player->start_time_ms = current_time_ms;",
            "            return true;",
            "        } else if (player->current_iteration >= player->animation->iterations) {",
            "            /* Animation finished */",
            "            player->is_playing = false;",
            "            return false;",
            "        } else {",
            "            /* Next iteration */",
            "            player->start_time_ms = current_time_ms;",
            "            return true;",
            "        }",
            "    }",
            "    ",
            "    return true;",
            "}",
            "",
            "float ui_animation_player_get_progress(ui_animation_player_t *player, uint32_t current_time_ms) {",
            "    if (!player->is_playing || !player->animation) {",
            "        return 0.0f;",
            "    }",
            "    ",
            "    uint32_t elapsed = current_time_ms - player->start_time_ms;",
            "    uint32_t duration = player->animation->duration_ms;",
            "    ",
            "    if (duration == 0) {",
            "        return 1.0f;",
            "    }",
            "    ",
            "    float t = (float)elapsed / (float)duration;",
            "    if (t > 1.0f) {",
            "        t = 1.0f;",
            "    }",
            "    ",
            "    return ui_easing_evaluate(player->animation->easing, t);",
            "}",
            ""
        ])
        
        return "\n".join(lines)
    
    def export_to_files(self, output_dir: Path, base_name: str = "ui_animations"):
        """Export animations to .h and .c files"""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate files
        header_file = output_dir / f"{base_name}.h"
        impl_file = output_dir / f"{base_name}.c"
        
        header_content = self.generate_header(f"{base_name}.h")
        impl_content = self.generate_implementation(f"{base_name}.c")
        
        # Write files
        header_file.write_text(header_content, encoding='utf-8')
        impl_file.write_text(impl_content, encoding='utf-8')
        
        print(f"✅ Exported to {header_file}")
        print(f"✅ Exported to {impl_file}")
        
        return header_file, impl_file
    
    def _sanitize_name(self, name: str) -> str:
        """Convert animation name to valid C identifier"""
        # Replace spaces and special chars with underscores
        safe = ''.join(c if c.isalnum() else '_' for c in name)
        # Remove consecutive underscores
        while '__' in safe:
            safe = safe.replace('__', '_')
        # Remove leading/trailing underscores
        safe = safe.strip('_')
        # Ensure doesn't start with digit
        if safe and safe[0].isdigit():
            safe = 'anim_' + safe
        return safe.lower()


def export_from_json(json_file: Path, output_dir: Path):
    """Export animations from JSON file to C code"""
    from ui_animations import AnimationDesigner
    
    # Load animations
    designer = AnimationDesigner()
    
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    if 'animations' in data:
        for anim_data in data['animations']:
            anim = Animation(**anim_data)
            designer.register_animation(anim)
    
    # Export
    exporter = AnimationExporter()
    for anim in designer.animations.values():
        exporter.add_animation(anim)
    
    exporter.export_to_files(output_dir)


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Export animations to C code")
    parser.add_argument("input", help="Input JSON file with animations")
    parser.add_argument("-o", "--output", default="exported_animations",
                       help="Output directory (default: exported_animations)")
    parser.add_argument("-n", "--name", default="ui_animations",
                       help="Base name for generated files (default: ui_animations)")
    
    args = parser.parse_args()
    
    input_file = Path(args.input)
    output_dir = Path(args.output)
    
    if not input_file.exists():
        print(f"❌ File not found: {input_file}")
        exit(1)
    
    export_from_json(input_file, output_dir)
    print(f"\n✅ Export complete! Files in {output_dir}/")
