#include "icons_registry.h"

#include <string.h>

/* AUTO-GENERATED by tools/gen_icons.py - do not edit by hand. */

typedef struct {
    const char *key; /* base key without prefix/suffix */
    const icon_t *icon16;
    const icon_t *icon24;
} icon_pair_t;

static const icon_pair_t k_icons[] = {
    {"arrow_back", &mi_arrow_back_16px, &mi_arrow_back_24px},
    {"arrow_forward", &mi_arrow_forward_16px, &mi_arrow_forward_24px},
    {"audio_file", &mi_audio_file_16px, &mi_audio_file_24px},
    {"battery_charging_full", &mi_battery_charging_full_16px, &mi_battery_charging_full_24px},
    {"battery_full", &mi_battery_full_16px, &mi_battery_full_24px},
    {"bluetooth", &mi_bluetooth_16px, &mi_bluetooth_24px},
    {"brightness_high", &mi_brightness_high_16px, &mi_brightness_high_24px},
    {"check", &mi_check_16px, &mi_check_24px},
    {"check_circle", &mi_check_circle_16px, &mi_check_circle_24px},
    {"close", &mi_close_16px, &mi_close_24px},
    {"cloud", &mi_cloud_16px, &mi_cloud_24px},
    {"cloud_download", &mi_cloud_download_16px, &mi_cloud_download_24px},
    {"cloud_upload", &mi_cloud_upload_16px, &mi_cloud_upload_24px},
    {"code", &mi_code_16px, &mi_code_24px},
    {"content_copy", &mi_content_copy_16px, &mi_content_copy_24px},
    {"content_paste", &mi_content_paste_16px, &mi_content_paste_24px},
    {"delete", &mi_delete_16px, &mi_delete_24px},
    {"description", &mi_description_16px, &mi_description_24px},
    {"drive_file_move", &mi_drive_file_move_16px, &mi_drive_file_move_24px},
    {"drive_file_rename_outline", &mi_drive_file_rename_outline_16px, &mi_drive_file_rename_outline_24px},
    {"error", &mi_error_16px, &mi_error_24px},
    {"file_upload", &mi_file_upload_16px, &mi_file_upload_24px},
    {"folder", &mi_folder_16px, &mi_folder_24px},
    {"folder_open", &mi_folder_open_16px, &mi_folder_open_24px},
    {"help", &mi_help_16px, &mi_help_24px},
    {"home", &mi_home_16px, &mi_home_24px},
    {"html", &mi_html_16px, &mi_html_24px},
    {"image", &mi_image_16px, &mi_image_24px},
    {"info", &mi_info_16px, &mi_info_24px},
    {"integration_instructions", &mi_integration_instructions_16px, &mi_integration_instructions_24px},
    {"javascript", &mi_javascript_16px, &mi_javascript_24px},
    {"lock", &mi_lock_16px, &mi_lock_24px},
    {"lock_open", &mi_lock_open_16px, &mi_lock_open_24px},
    {"menu", &mi_menu_16px, &mi_menu_24px},
    {"more_horiz", &mi_more_horiz_16px, &mi_more_horiz_24px},
    {"more_vert", &mi_more_vert_16px, &mi_more_vert_24px},
    {"network_wifi", &mi_network_wifi_16px, &mi_network_wifi_24px},
    {"pause", &mi_pause_16px, &mi_pause_24px},
    {"picture_as_pdf", &mi_picture_as_pdf_16px, &mi_picture_as_pdf_24px},
    {"play_arrow", &mi_play_arrow_16px, &mi_play_arrow_24px},
    {"power_settings_new", &mi_power_settings_new_16px, &mi_power_settings_new_24px},
    {"save", &mi_save_16px, &mi_save_24px},
    {"save_alt", &mi_save_alt_16px, &mi_save_alt_24px},
    {"sd_storage", &mi_sd_storage_16px, &mi_sd_storage_24px},
    {"search", &mi_search_16px, &mi_search_24px},
    {"settings", &mi_settings_16px, &mi_settings_24px},
    {"stop", &mi_stop_16px, &mi_stop_24px},
    {"text_snippet", &mi_text_snippet_16px, &mi_text_snippet_24px},
    {"upload_file", &mi_upload_file_16px, &mi_upload_file_24px},
    {"video_file", &mi_video_file_16px, &mi_video_file_24px},
    {"volume_off", &mi_volume_off_16px, &mi_volume_off_24px},
    {"volume_up", &mi_volume_up_16px, &mi_volume_up_24px},
    {"warning", &mi_warning_16px, &mi_warning_24px},
};

static int ends_with(const char *s, const char *suffix)
{
    size_t sl = (s != NULL) ? strlen(s) : 0;
    size_t tl = (suffix != NULL) ? strlen(suffix) : 0;
    if (sl < tl) {
        return 0;
    }
    return memcmp(s + (sl - tl), suffix, tl) == 0;
}

static void normalize_key(const char *name, char *out, size_t out_cap)
{
    if (out == NULL || out_cap == 0) {
        return;
    }
    out[0] = '\0';
    if (name == NULL || *name == '\0') {
        return;
    }

    const char *p = name;
    if (strncmp(p, "mi_", 3) == 0) {
        p += 3;
    }
    size_t n = strnlen(p, out_cap - 1);
    memcpy(out, p, n);
    out[n] = '\0';

    if (ends_with(out, "_16px")) {
        out[n - 5] = '\0';
        return;
    }
    if (ends_with(out, "_24px")) {
        out[n - 5] = '\0';
        return;
    }
}

const icon_t *icons_find(const char *name, uint8_t size_px)
{
    if (name == NULL || *name == '\0') {
        return NULL;
    }

    char key[64];
    normalize_key(name, key, sizeof(key));
    if (key[0] == '\0') {
        return NULL;
    }

    const size_t count = sizeof(k_icons) / sizeof(k_icons[0]);
    for (size_t i = 0; i < count; ++i) {
        const icon_pair_t *p = &k_icons[i];
        if (strcmp(p->key, key) != 0) {
            continue;
        }
        if (size_px >= 24 && p->icon24 != NULL) {
            return p->icon24;
        }
        if (p->icon16 != NULL) {
            return p->icon16;
        }
        return p->icon24;
    }
    return NULL;
}

