#pragma once

#include <stdint.h>
#include "icons.h"

/* AUTO-GENERATED by tools/gen_icons.py - do not edit by hand. */

/* Find an icon by name.
 *
 * Accepted forms: "arrow_back", "mi_arrow_back", "mi_arrow_back_16px", "mi_arrow_back_24px".
 * size_px: requested pixel size (e.g. 16 or 24). Nearest available is returned.
 */
const icon_t *icons_find(const char *name, uint8_t size_px);

