/* Auto-generated: UI design for ESP32OS */
/* Source: main_scene.json (scene: main) */
#include "ui_design.h"

/* String pool */
static const char str_0[] = "status_bar.left";
static const char str_1[] = "ESP32OS";
static const char str_2[] = "status_bar.right";
static const char str_3[] = "menu.panel";
static const char str_4[] = "menu.title";
static const char str_5[] = "Menu";
static const char str_6[] = "menu.scroll";
static const char str_7[] = "1/3";
static const char str_8[] = "menu.item0";
static const char str_9[] = "Display";
static const char str_10[] = "menu.item1";
static const char str_11[] = "Inputs";
static const char str_12[] = "menu.item2";
static const char str_13[] = "About";
static const char str_14[] = "menu.item3";
static const char str_15[] = "menu.item4";
static const char str_16[] = "list.panel";
static const char str_17[] = "list.title";
static const char str_18[] = "list.scroll";
static const char str_19[] = "1/12";
static const char str_20[] = "list.item0";
static const char str_21[] = "list.item0.label";
static const char str_22[] = "Contrast";
static const char str_23[] = "list.item0.value";
static const char str_24[] = "0";
static const char str_25[] = "list.item1";
static const char str_26[] = "list.item1.label";
static const char str_27[] = "Invert";
static const char str_28[] = "list.item1.value";
static const char str_29[] = "off";
static const char str_30[] = "list.item2";
static const char str_31[] = "list.item2.label";
static const char str_32[] = "ColOffset";
static const char str_33[] = "list.item2.value";
static const char str_34[] = "list.item3";
static const char str_35[] = "list.item3.label";
static const char str_36[] = "list.item3.value";
static const char str_37[] = "list.item4";
static const char str_38[] = "list.item4.label";
static const char str_39[] = "list.item4.value";
static const char str_40[] = "edit.panel";
static const char str_41[] = "edit.title";
static const char str_42[] = "Edit";
static const char str_43[] = "edit.hint";
static const char str_44[] = "UP/DOWN adjust  B back";
static const char str_45[] = "edit_contrast.value";
static const char str_46[] = "bind=contrast;kind=int;min=0;max=255;step=8;suffix= /255";
static const char str_47[] = "edit_invert.value";
static const char str_48[] = "bind=invert;kind=bool;values=off|on";
static const char str_49[] = "edit_col_offset.value";
static const char str_50[] = "bind=col_offset;kind=int;min=0;max=16;step=1;suffix= px";
static const char str_51[] = "toast.panel";
static const char str_52[] = "toast.message";
static const char str_53[] = "Toast";

/* Widget definitions */
static const UiWidget widgets[] = {
    { /* [0] UIW_PANEL "" */
        .type = UIW_PANEL,
        .x = 8, .y = 16, .width = 246, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = NULL,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [1] UIW_LABEL "ESP32OS" */
        .type = UIW_LABEL,
        .x = 8, .y = 40, .width = 160, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_0,
        .text = str_1,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 1, .enabled = 1,
    },
    { /* [2] UIW_LABEL "status_bar.right" */
        .type = UIW_LABEL,
        .x = 8, .y = 64, .width = 84, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_2,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [3] UIW_PANEL "" */
        .type = UIW_PANEL,
        .x = 8, .y = 88, .width = 246, .height = 38,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = NULL,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [4] UIW_PANEL "menu.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 208, .width = 240, .height = 104,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_3,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [5] UIW_LABEL "Menu" */
        .type = UIW_LABEL,
        .x = 8, .y = 320, .width = 172, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_4,
        .text = str_5,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 1, .enabled = 1,
    },
    { /* [6] UIW_LABEL "1/3" */
        .type = UIW_LABEL,
        .x = 188, .y = 320, .width = 48, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_6,
        .text = str_7,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [7] UIW_BUTTON "Display" */
        .type = UIW_BUTTON,
        .x = 8, .y = 344, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_8,
        .text = str_9,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_HIGHLIGHT,
        .visible = 1, .enabled = 1,
    },
    { /* [8] UIW_BUTTON "Inputs" */
        .type = UIW_BUTTON,
        .x = 8, .y = 368, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_10,
        .text = str_11,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [9] UIW_BUTTON "About" */
        .type = UIW_BUTTON,
        .x = 8, .y = 392, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_12,
        .text = str_13,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [10] UIW_BUTTON "menu.item3" */
        .type = UIW_BUTTON,
        .x = 8, .y = 416, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_14,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 0,
    },
    { /* [11] UIW_BUTTON "menu.item4" */
        .type = UIW_BUTTON,
        .x = 8, .y = 440, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_15,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 0,
    },
    { /* [12] UIW_PANEL "list.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 464, .width = 240, .height = 104,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_16,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [13] UIW_LABEL "Display" */
        .type = UIW_LABEL,
        .x = 8, .y = 576, .width = 172, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_17,
        .text = str_9,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 0, .enabled = 1,
    },
    { /* [14] UIW_LABEL "1/12" */
        .type = UIW_LABEL,
        .x = 188, .y = 576, .width = 48, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_18,
        .text = str_19,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [15] UIW_BUTTON "list.item0" */
        .type = UIW_BUTTON,
        .x = 8, .y = 600, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_20,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_HIGHLIGHT,
        .visible = 0, .enabled = 1,
    },
    { /* [16] UIW_LABEL "Contrast" */
        .type = UIW_LABEL,
        .x = 8, .y = 624, .width = 144, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_21,
        .text = str_22,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [17] UIW_LABEL "0" */
        .type = UIW_LABEL,
        .x = 160, .y = 624, .width = 72, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_23,
        .text = str_24,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [18] UIW_BUTTON "list.item1" */
        .type = UIW_BUTTON,
        .x = 8, .y = 648, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_25,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [19] UIW_LABEL "Invert" */
        .type = UIW_LABEL,
        .x = 8, .y = 672, .width = 144, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_26,
        .text = str_27,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [20] UIW_LABEL "off" */
        .type = UIW_LABEL,
        .x = 160, .y = 672, .width = 72, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_28,
        .text = str_29,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [21] UIW_BUTTON "list.item2" */
        .type = UIW_BUTTON,
        .x = 8, .y = 696, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_30,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [22] UIW_LABEL "ColOffset" */
        .type = UIW_LABEL,
        .x = 8, .y = 720, .width = 144, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_31,
        .text = str_32,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [23] UIW_LABEL "0" */
        .type = UIW_LABEL,
        .x = 160, .y = 720, .width = 72, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_33,
        .text = str_24,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [24] UIW_BUTTON "list.item3" */
        .type = UIW_BUTTON,
        .x = 8, .y = 744, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_34,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [25] UIW_LABEL "list.item3.label" */
        .type = UIW_LABEL,
        .x = 8, .y = 768, .width = 144, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_35,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [26] UIW_LABEL "list.item3.value" */
        .type = UIW_LABEL,
        .x = 160, .y = 768, .width = 72, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_36,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [27] UIW_BUTTON "list.item4" */
        .type = UIW_BUTTON,
        .x = 8, .y = 792, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_37,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [28] UIW_LABEL "list.item4.label" */
        .type = UIW_LABEL,
        .x = 8, .y = 816, .width = 144, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_38,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [29] UIW_LABEL "list.item4.value" */
        .type = UIW_LABEL,
        .x = 160, .y = 816, .width = 72, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_39,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [30] UIW_PANEL "edit.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 840, .width = 240, .height = 104,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_40,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [31] UIW_LABEL "Edit" */
        .type = UIW_LABEL,
        .x = 8, .y = 952, .width = 224, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_41,
        .text = str_42,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 13, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 0, .enabled = 1,
    },
    { /* [32] UIW_LABEL "UP/DOWN adjust  B back" */
        .type = UIW_LABEL,
        .x = 8, .y = 976, .width = 224, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_43,
        .text = str_44,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 9, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [33] UIW_BUTTON "Contrast" */
        .type = UIW_BUTTON,
        .x = 8, .y = 1000, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_45,
        .text = str_22,
        .constraints_json = str_46,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [34] UIW_BUTTON "Invert" */
        .type = UIW_BUTTON,
        .x = 8, .y = 1024, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_47,
        .text = str_27,
        .constraints_json = str_48,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [35] UIW_BUTTON "ColOffset" */
        .type = UIW_BUTTON,
        .x = 8, .y = 1048, .width = 224, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_49,
        .text = str_32,
        .constraints_json = str_50,
        .animations_csv = NULL,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [36] UIW_PANEL "toast.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 1072, .width = 240, .height = 20,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_51,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [37] UIW_LABEL "Toast" */
        .type = UIW_LABEL,
        .x = 8, .y = 1100, .width = 232, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_52,
        .text = str_53,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
};

/* Scene definition */
const UiScene ui_design = {
    .name = "main",
    .width = 256,
    .height = 128,
    .widget_count = (uint16_t)(sizeof(widgets) / sizeof(widgets[0])),
    .widgets = widgets,
};
