/* Auto-generated: UI design for ESP32OS (multi-scene) */
/* Source: main_scene.json */
#include "ui_design.h"

/* String pool */
static const char str_0[] = "main.title";
static const char str_1[] = "ESP32OS";
static const char str_2[] = "main.scene_ind";
static const char str_3[] = "1/4";
static const char str_4[] = "main.panel";
static const char str_5[] = "main.brand";
static const char str_6[] = "main.subtitle";
static const char str_7[] = "embedded UI";
static const char str_8[] = "main.hint";
static const char str_9[] = "B=back  C=next";
static const char str_10[] = "toast.panel";
static const char str_11[] = "toast.message";
static const char str_12[] = "Toast";
static const char str_13[] = "menu.title";
static const char str_14[] = "Menu";
static const char str_15[] = "menu.scene_ind";
static const char str_16[] = "2/4";
static const char str_17[] = "menu.panel";
static const char str_18[] = "menu.scroll";
static const char str_19[] = "1/3";
static const char str_20[] = "menu.item0";
static const char str_21[] = "Display";
static const char str_22[] = "menu.item1";
static const char str_23[] = "Inputs";
static const char str_24[] = "menu.item2";
static const char str_25[] = "About";
static const char str_26[] = "menu.hint";
static const char str_27[] = "A=select  B=back  C=next";
static const char str_28[] = "settings.title";
static const char str_29[] = "Settings";
static const char str_30[] = "settings.scene_ind";
static const char str_31[] = "3/4";
static const char str_32[] = "set.contrast.label";
static const char str_33[] = "Contrast";
static const char str_34[] = "set.contrast";
static const char str_35[] = "bind=contrast";
static const char str_36[] = "set.invert.label";
static const char str_37[] = "Invert";
static const char str_38[] = "set.invert";
static const char str_39[] = "bind=invert";
static const char str_40[] = "set.coloffset.label";
static const char str_41[] = "ColOffset";
static const char str_42[] = "set.coloffset";
static const char str_43[] = "bind=col_offset";
static const char str_44[] = "settings.hint";
static const char str_45[] = "A=edit  B=back  C=next";
static const char str_46[] = "settings.status";
static const char str_47[] = "metrics.title";
static const char str_48[] = "Metrics";
static const char str_49[] = "metrics.scene_ind";
static const char str_50[] = "4/4";
static const char str_51[] = "metrics.heap.label";
static const char str_52[] = "Heap";
static const char str_53[] = "metrics.heap";
static const char str_54[] = "75%";
static const char str_55[] = "metrics.minheap.label";
static const char str_56[] = "MinHeap";
static const char str_57[] = "metrics.minheap";
static const char str_58[] = "50%";
static const char str_59[] = "metrics.uptime.label";
static const char str_60[] = "Uptime";
static const char str_61[] = "metrics.uptime";
static const char str_62[] = "metrics.chart.label";
static const char str_63[] = "History";
static const char str_64[] = "metrics.chart";
static const char str_65[] = "metrics.free_text";
static const char str_66[] = "Free: --";
static const char str_67[] = "metrics.min_text";
static const char str_68[] = "Min: --";
static const char str_69[] = "metrics.hint";

/* Scene: main (9 widgets) */
static const UiWidget main_widgets[] = {
    { /* [0] UIW_PANEL "" */
        .type = UIW_PANEL,
        .x = 0, .y = 0, .width = 256, .height = 14,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = NULL,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [1] UIW_LABEL "ESP32OS" */
        .type = UIW_LABEL,
        .x = 2, .y = 0, .width = 150, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_0,
        .text = str_1,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 1, .enabled = 1,
    },
    { /* [2] UIW_LABEL "1/4" */
        .type = UIW_LABEL,
        .x = 200, .y = 0, .width = 54, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_2,
        .text = str_3,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 8, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [3] UIW_PANEL "main.panel" */
        .type = UIW_PANEL,
        .x = 4, .y = 18, .width = 248, .height = 70,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_4,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [4] UIW_LABEL "ESP32OS" */
        .type = UIW_LABEL,
        .x = 12, .y = 32, .width = 232, .height = 18,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_5,
        .text = str_1,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 13, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 1, .enabled = 1,
    },
    { /* [5] UIW_LABEL "embedded UI" */
        .type = UIW_LABEL,
        .x = 12, .y = 56, .width = 232, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_6,
        .text = str_7,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 9, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [6] UIW_LABEL "B=back  C=next" */
        .type = UIW_LABEL,
        .x = 4, .y = 90, .width = 248, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_8,
        .text = str_9,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 6, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [7] UIW_PANEL "toast.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 104, .width = 240, .height = 18,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_10,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [8] UIW_LABEL "Toast" */
        .type = UIW_LABEL,
        .x = 12, .y = 107, .width = 232, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_11,
        .text = str_12,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
};

/* Scene: menu (11 widgets) */
static const UiWidget menu_widgets[] = {
    { /* [0] UIW_PANEL "" */
        .type = UIW_PANEL,
        .x = 0, .y = 0, .width = 256, .height = 14,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = NULL,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [1] UIW_LABEL "Menu" */
        .type = UIW_LABEL,
        .x = 2, .y = 0, .width = 150, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_13,
        .text = str_14,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 1, .enabled = 1,
    },
    { /* [2] UIW_LABEL "2/4" */
        .type = UIW_LABEL,
        .x = 200, .y = 0, .width = 54, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_15,
        .text = str_16,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 8, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [3] UIW_PANEL "menu.panel" */
        .type = UIW_PANEL,
        .x = 2, .y = 16, .width = 252, .height = 72,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_17,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 0,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [4] UIW_LABEL "1/3" */
        .type = UIW_LABEL,
        .x = 192, .y = 19, .width = 58, .height = 10,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_18,
        .text = str_19,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 14, .bg = 1,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [5] UIW_BUTTON "Display" */
        .type = UIW_BUTTON,
        .x = 8, .y = 32, .width = 240, .height = 15,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_20,
        .text = str_21,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_HIGHLIGHT,
        .visible = 1, .enabled = 1,
    },
    { /* [6] UIW_BUTTON "Inputs" */
        .type = UIW_BUTTON,
        .x = 8, .y = 51, .width = 240, .height = 15,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_22,
        .text = str_23,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [7] UIW_BUTTON "About" */
        .type = UIW_BUTTON,
        .x = 8, .y = 70, .width = 240, .height = 15,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_24,
        .text = str_25,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 14, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [8] UIW_LABEL "A=select  B=back  C=next" */
        .type = UIW_LABEL,
        .x = 4, .y = 92, .width = 248, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_26,
        .text = str_27,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 6, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [9] UIW_PANEL "toast.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 104, .width = 240, .height = 18,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_10,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [10] UIW_LABEL "Toast" */
        .type = UIW_LABEL,
        .x = 12, .y = 107, .width = 232, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_11,
        .text = str_12,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
};

/* Scene: settings (14 widgets) */
static const UiWidget settings_widgets[] = {
    { /* [0] UIW_PANEL "" */
        .type = UIW_PANEL,
        .x = 0, .y = 0, .width = 256, .height = 14,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = NULL,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [1] UIW_LABEL "Settings" */
        .type = UIW_LABEL,
        .x = 2, .y = 0, .width = 100, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_28,
        .text = str_29,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 1, .enabled = 1,
    },
    { /* [2] UIW_LABEL "3/4" */
        .type = UIW_LABEL,
        .x = 200, .y = 0, .width = 54, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_30,
        .text = str_31,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 8, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [3] UIW_LABEL "Contrast" */
        .type = UIW_LABEL,
        .x = 4, .y = 18, .width = 80, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_32,
        .text = str_33,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [4] UIW_SLIDER "set.contrast" */
        .type = UIW_SLIDER,
        .x = 88, .y = 18, .width = 160, .height = 16,
        .border = 1, .checked = 0,
        .value = 127, .min_value = 0, .max_value = 255,
        .id = str_34,
        .text = NULL,
        .constraints_json = str_35,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [5] UIW_LABEL "Invert" */
        .type = UIW_LABEL,
        .x = 4, .y = 38, .width = 80, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_36,
        .text = str_37,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [6] UIW_CHECKBOX "set.invert" */
        .type = UIW_CHECKBOX,
        .x = 88, .y = 38, .width = 16, .height = 16,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_38,
        .text = NULL,
        .constraints_json = str_39,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [7] UIW_LABEL "ColOffset" */
        .type = UIW_LABEL,
        .x = 4, .y = 58, .width = 80, .height = 16,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_40,
        .text = str_41,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [8] UIW_SLIDER "set.coloffset" */
        .type = UIW_SLIDER,
        .x = 88, .y = 58, .width = 160, .height = 16,
        .border = 1, .checked = 0,
        .value = 28, .min_value = 0, .max_value = 63,
        .id = str_42,
        .text = NULL,
        .constraints_json = str_43,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [9] UIW_BOX "" */
        .type = UIW_BOX,
        .x = 4, .y = 78, .width = 248, .height = 1,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = NULL,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 4, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [10] UIW_LABEL "A=edit  B=back  C=next" */
        .type = UIW_LABEL,
        .x = 4, .y = 82, .width = 248, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_44,
        .text = str_45,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 6, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [11] UIW_LABEL "settings.status" */
        .type = UIW_LABEL,
        .x = 4, .y = 98, .width = 248, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_46,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 8, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [12] UIW_PANEL "toast.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 104, .width = 240, .height = 18,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_10,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [13] UIW_LABEL "Toast" */
        .type = UIW_LABEL,
        .x = 12, .y = 107, .width = 232, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_11,
        .text = str_12,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
};

/* Scene: metrics (16 widgets) */
static const UiWidget metrics_widgets[] = {
    { /* [0] UIW_PANEL "" */
        .type = UIW_PANEL,
        .x = 0, .y = 0, .width = 256, .height = 14,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = NULL,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [1] UIW_LABEL "Metrics" */
        .type = UIW_LABEL,
        .x = 2, .y = 0, .width = 100, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_47,
        .text = str_48,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 13, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_BOLD,
        .visible = 1, .enabled = 1,
    },
    { /* [2] UIW_LABEL "4/4" */
        .type = UIW_LABEL,
        .x = 200, .y = 0, .width = 54, .height = 14,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_49,
        .text = str_50,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 8, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_RIGHT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [3] UIW_LABEL "Heap" */
        .type = UIW_LABEL,
        .x = 4, .y = 16, .width = 60, .height = 10,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_51,
        .text = str_52,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 11, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [4] UIW_GAUGE "75%" */
        .type = UIW_GAUGE,
        .x = 4, .y = 26, .width = 60, .height = 48,
        .border = 1, .checked = 0,
        .value = 75, .min_value = 0, .max_value = 100,
        .id = str_53,
        .text = str_54,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [5] UIW_LABEL "MinHeap" */
        .type = UIW_LABEL,
        .x = 68, .y = 16, .width = 60, .height = 10,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_55,
        .text = str_56,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 11, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [6] UIW_GAUGE "50%" */
        .type = UIW_GAUGE,
        .x = 68, .y = 26, .width = 60, .height = 48,
        .border = 1, .checked = 0,
        .value = 50, .min_value = 0, .max_value = 100,
        .id = str_57,
        .text = str_58,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [7] UIW_LABEL "Uptime" */
        .type = UIW_LABEL,
        .x = 132, .y = 16, .width = 120, .height = 10,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_59,
        .text = str_60,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 11, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [8] UIW_PROGRESSBAR "metrics.uptime" */
        .type = UIW_PROGRESSBAR,
        .x = 132, .y = 26, .width = 120, .height = 14,
        .border = 1, .checked = 0,
        .value = 60, .min_value = 0, .max_value = 100,
        .id = str_61,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [9] UIW_LABEL "History" */
        .type = UIW_LABEL,
        .x = 132, .y = 44, .width = 120, .height = 10,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_62,
        .text = str_63,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 11, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [10] UIW_CHART "metrics.chart" */
        .type = UIW_CHART,
        .x = 132, .y = 54, .width = 120, .height = 36,
        .border = 1, .checked = 0,
        .value = 60, .min_value = 0, .max_value = 100,
        .id = str_64,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [11] UIW_LABEL "Free: --" */
        .type = UIW_LABEL,
        .x = 4, .y = 78, .width = 124, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_65,
        .text = str_66,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 9, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [12] UIW_LABEL "Min: --" */
        .type = UIW_LABEL,
        .x = 4, .y = 92, .width = 124, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_67,
        .text = str_68,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 9, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [13] UIW_LABEL "B=back  C=next" */
        .type = UIW_LABEL,
        .x = 4, .y = 108, .width = 248, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_69,
        .text = str_9,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 6, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_CENTER, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 1, .enabled = 1,
    },
    { /* [14] UIW_PANEL "toast.panel" */
        .type = UIW_PANEL,
        .x = 8, .y = 104, .width = 240, .height = 18,
        .border = 1, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_10,
        .text = NULL,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_SINGLE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
    { /* [15] UIW_LABEL "Toast" */
        .type = UIW_LABEL,
        .x = 12, .y = 107, .width = 232, .height = 12,
        .border = 0, .checked = 0,
        .value = 0, .min_value = 0, .max_value = 100,
        .id = str_11,
        .text = str_12,
        .constraints_json = NULL,
        .animations_csv = NULL,
        .icon_char = NULL,
        .data_points = NULL,
        .data_count = 0,
        .fg = 15, .bg = 0,
        .border_style = UI_BORDER_NONE,
        .align = UI_ALIGN_LEFT, .valign = UI_VALIGN_MIDDLE,
        .text_overflow = UI_TEXT_OVERFLOW_ELLIPSIS, .max_lines = 1,
        .style = UI_STYLE_NONE,
        .visible = 0, .enabled = 1,
    },
};

/* Scene registry */
const UiScene ui_scenes[] = {
    { /* main */
        .name = "main",
        .width = 256, .height = 128,
        .widget_count = (uint16_t)(sizeof(main_widgets) / sizeof(main_widgets[0])),
        .widgets = main_widgets,
    },
    { /* menu */
        .name = "menu",
        .width = 256, .height = 128,
        .widget_count = (uint16_t)(sizeof(menu_widgets) / sizeof(menu_widgets[0])),
        .widgets = menu_widgets,
    },
    { /* settings */
        .name = "settings",
        .width = 256, .height = 128,
        .widget_count = (uint16_t)(sizeof(settings_widgets) / sizeof(settings_widgets[0])),
        .widgets = settings_widgets,
    },
    { /* metrics */
        .name = "metrics",
        .width = 256, .height = 128,
        .widget_count = (uint16_t)(sizeof(metrics_widgets) / sizeof(metrics_widgets[0])),
        .widgets = metrics_widgets,
    },
};
